/*
mm-gateway

Unified image, video, and music gateway with separate REST APIs.

API version: 0.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package mmgateway

import (
	"encoding/json"
	"fmt"
)

// checks if the VideoOutput type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &VideoOutput{}

// VideoOutput struct for VideoOutput
type VideoOutput struct {
	// Absolute media URI. Inline media uses a base64 data URI.
	CoverUri NullableString `json:"cover_uri,omitempty"`
	MimeType NullableString `json:"mime_type,omitempty"`
	// Absolute media URI. Inline media uses a base64 data URI.
	Uri string `json:"uri"`
	AdditionalProperties map[string]interface{}
}

type _VideoOutput VideoOutput

// NewVideoOutput instantiates a new VideoOutput object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewVideoOutput(uri string) *VideoOutput {
	this := VideoOutput{}
	this.Uri = uri
	return &this
}

// NewVideoOutputWithDefaults instantiates a new VideoOutput object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewVideoOutputWithDefaults() *VideoOutput {
	this := VideoOutput{}
	return &this
}

// GetCoverUri returns the CoverUri field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *VideoOutput) GetCoverUri() string {
	if o == nil || IsNil(o.CoverUri.Get()) {
		var ret string
		return ret
	}
	return *o.CoverUri.Get()
}

// GetCoverUriOk returns a tuple with the CoverUri field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *VideoOutput) GetCoverUriOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.CoverUri.Get(), o.CoverUri.IsSet()
}

// HasCoverUri returns a boolean if a field has been set.
func (o *VideoOutput) HasCoverUri() bool {
	if o != nil && o.CoverUri.IsSet() {
		return true
	}

	return false
}

// SetCoverUri gets a reference to the given NullableString and assigns it to the CoverUri field.
func (o *VideoOutput) SetCoverUri(v string) {
	o.CoverUri.Set(&v)
}
// SetCoverUriNil sets the value for CoverUri to be an explicit nil
func (o *VideoOutput) SetCoverUriNil() {
	o.CoverUri.Set(nil)
}

// UnsetCoverUri ensures that no value is present for CoverUri, not even an explicit nil
func (o *VideoOutput) UnsetCoverUri() {
	o.CoverUri.Unset()
}

// GetMimeType returns the MimeType field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *VideoOutput) GetMimeType() string {
	if o == nil || IsNil(o.MimeType.Get()) {
		var ret string
		return ret
	}
	return *o.MimeType.Get()
}

// GetMimeTypeOk returns a tuple with the MimeType field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *VideoOutput) GetMimeTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.MimeType.Get(), o.MimeType.IsSet()
}

// HasMimeType returns a boolean if a field has been set.
func (o *VideoOutput) HasMimeType() bool {
	if o != nil && o.MimeType.IsSet() {
		return true
	}

	return false
}

// SetMimeType gets a reference to the given NullableString and assigns it to the MimeType field.
func (o *VideoOutput) SetMimeType(v string) {
	o.MimeType.Set(&v)
}
// SetMimeTypeNil sets the value for MimeType to be an explicit nil
func (o *VideoOutput) SetMimeTypeNil() {
	o.MimeType.Set(nil)
}

// UnsetMimeType ensures that no value is present for MimeType, not even an explicit nil
func (o *VideoOutput) UnsetMimeType() {
	o.MimeType.Unset()
}

// GetUri returns the Uri field value
func (o *VideoOutput) GetUri() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Uri
}

// GetUriOk returns a tuple with the Uri field value
// and a boolean to check if the value has been set.
func (o *VideoOutput) GetUriOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Uri, true
}

// SetUri sets field value
func (o *VideoOutput) SetUri(v string) {
	o.Uri = v
}

func (o VideoOutput) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o VideoOutput) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if o.CoverUri.IsSet() {
		toSerialize["cover_uri"] = o.CoverUri.Get()
	}
	if o.MimeType.IsSet() {
		toSerialize["mime_type"] = o.MimeType.Get()
	}
	toSerialize["uri"] = o.Uri

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *VideoOutput) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"uri",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varVideoOutput := _VideoOutput{}

	err = json.Unmarshal(data, &varVideoOutput)

	if err != nil {
		return err
	}

	*o = VideoOutput(varVideoOutput)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "cover_uri")
		delete(additionalProperties, "mime_type")
		delete(additionalProperties, "uri")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableVideoOutput struct {
	value *VideoOutput
	isSet bool
}

func (v NullableVideoOutput) Get() *VideoOutput {
	return v.value
}

func (v *NullableVideoOutput) Set(val *VideoOutput) {
	v.value = val
	v.isSet = true
}

func (v NullableVideoOutput) IsSet() bool {
	return v.isSet
}

func (v *NullableVideoOutput) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableVideoOutput(val *VideoOutput) *NullableVideoOutput {
	return &NullableVideoOutput{value: val, isSet: true}
}

func (v NullableVideoOutput) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableVideoOutput) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


