/*
mm-gateway

Provider-neutral image, video, music, speech and voice cloning gateway.

API version: 0.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package mmgateway

import (
	"encoding/json"
)

// checks if the ManagementConfigOutput type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ManagementConfigOutput{}

// ManagementConfigOutput struct for ManagementConfigOutput
type ManagementConfigOutput struct {
	Backends []ManagedBackend `json:"backends,omitempty"`
	BudgetAllowUnpriced *bool `json:"budget_allow_unpriced,omitempty"`
	CatalogModels map[string]interface{} `json:"catalog_models,omitempty"`
	Keys []ManagedKey `json:"keys,omitempty"`
	OutboundProxy NullableString `json:"outbound_proxy,omitempty"`
	Proxies []ManagedProxy `json:"proxies,omitempty"`
	RoutingDefaultOptimize *string `json:"routing_default_optimize,omitempty"`
	RoutingProfiles map[string]ManagedRoutingProfile `json:"routing_profiles,omitempty"`
}

// NewManagementConfigOutput instantiates a new ManagementConfigOutput object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewManagementConfigOutput() *ManagementConfigOutput {
	this := ManagementConfigOutput{}
	var budgetAllowUnpriced bool = false
	this.BudgetAllowUnpriced = &budgetAllowUnpriced
	var routingDefaultOptimize string = "balanced"
	this.RoutingDefaultOptimize = &routingDefaultOptimize
	return &this
}

// NewManagementConfigOutputWithDefaults instantiates a new ManagementConfigOutput object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewManagementConfigOutputWithDefaults() *ManagementConfigOutput {
	this := ManagementConfigOutput{}
	var budgetAllowUnpriced bool = false
	this.BudgetAllowUnpriced = &budgetAllowUnpriced
	var routingDefaultOptimize string = "balanced"
	this.RoutingDefaultOptimize = &routingDefaultOptimize
	return &this
}

// GetBackends returns the Backends field value if set, zero value otherwise.
func (o *ManagementConfigOutput) GetBackends() []ManagedBackend {
	if o == nil || IsNil(o.Backends) {
		var ret []ManagedBackend
		return ret
	}
	return o.Backends
}

// GetBackendsOk returns a tuple with the Backends field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ManagementConfigOutput) GetBackendsOk() ([]ManagedBackend, bool) {
	if o == nil || IsNil(o.Backends) {
		return nil, false
	}
	return o.Backends, true
}

// HasBackends returns a boolean if a field has been set.
func (o *ManagementConfigOutput) HasBackends() bool {
	if o != nil && !IsNil(o.Backends) {
		return true
	}

	return false
}

// SetBackends gets a reference to the given []ManagedBackend and assigns it to the Backends field.
func (o *ManagementConfigOutput) SetBackends(v []ManagedBackend) {
	o.Backends = v
}

// GetBudgetAllowUnpriced returns the BudgetAllowUnpriced field value if set, zero value otherwise.
func (o *ManagementConfigOutput) GetBudgetAllowUnpriced() bool {
	if o == nil || IsNil(o.BudgetAllowUnpriced) {
		var ret bool
		return ret
	}
	return *o.BudgetAllowUnpriced
}

// GetBudgetAllowUnpricedOk returns a tuple with the BudgetAllowUnpriced field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ManagementConfigOutput) GetBudgetAllowUnpricedOk() (*bool, bool) {
	if o == nil || IsNil(o.BudgetAllowUnpriced) {
		return nil, false
	}
	return o.BudgetAllowUnpriced, true
}

// HasBudgetAllowUnpriced returns a boolean if a field has been set.
func (o *ManagementConfigOutput) HasBudgetAllowUnpriced() bool {
	if o != nil && !IsNil(o.BudgetAllowUnpriced) {
		return true
	}

	return false
}

// SetBudgetAllowUnpriced gets a reference to the given bool and assigns it to the BudgetAllowUnpriced field.
func (o *ManagementConfigOutput) SetBudgetAllowUnpriced(v bool) {
	o.BudgetAllowUnpriced = &v
}

// GetCatalogModels returns the CatalogModels field value if set, zero value otherwise.
func (o *ManagementConfigOutput) GetCatalogModels() map[string]interface{} {
	if o == nil || IsNil(o.CatalogModels) {
		var ret map[string]interface{}
		return ret
	}
	return o.CatalogModels
}

// GetCatalogModelsOk returns a tuple with the CatalogModels field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ManagementConfigOutput) GetCatalogModelsOk() (map[string]interface{}, bool) {
	if o == nil || IsNil(o.CatalogModels) {
		return map[string]interface{}{}, false
	}
	return o.CatalogModels, true
}

// HasCatalogModels returns a boolean if a field has been set.
func (o *ManagementConfigOutput) HasCatalogModels() bool {
	if o != nil && !IsNil(o.CatalogModels) {
		return true
	}

	return false
}

// SetCatalogModels gets a reference to the given map[string]interface{} and assigns it to the CatalogModels field.
func (o *ManagementConfigOutput) SetCatalogModels(v map[string]interface{}) {
	o.CatalogModels = v
}

// GetKeys returns the Keys field value if set, zero value otherwise.
func (o *ManagementConfigOutput) GetKeys() []ManagedKey {
	if o == nil || IsNil(o.Keys) {
		var ret []ManagedKey
		return ret
	}
	return o.Keys
}

// GetKeysOk returns a tuple with the Keys field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ManagementConfigOutput) GetKeysOk() ([]ManagedKey, bool) {
	if o == nil || IsNil(o.Keys) {
		return nil, false
	}
	return o.Keys, true
}

// HasKeys returns a boolean if a field has been set.
func (o *ManagementConfigOutput) HasKeys() bool {
	if o != nil && !IsNil(o.Keys) {
		return true
	}

	return false
}

// SetKeys gets a reference to the given []ManagedKey and assigns it to the Keys field.
func (o *ManagementConfigOutput) SetKeys(v []ManagedKey) {
	o.Keys = v
}

// GetOutboundProxy returns the OutboundProxy field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *ManagementConfigOutput) GetOutboundProxy() string {
	if o == nil || IsNil(o.OutboundProxy.Get()) {
		var ret string
		return ret
	}
	return *o.OutboundProxy.Get()
}

// GetOutboundProxyOk returns a tuple with the OutboundProxy field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ManagementConfigOutput) GetOutboundProxyOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.OutboundProxy.Get(), o.OutboundProxy.IsSet()
}

// HasOutboundProxy returns a boolean if a field has been set.
func (o *ManagementConfigOutput) HasOutboundProxy() bool {
	if o != nil && o.OutboundProxy.IsSet() {
		return true
	}

	return false
}

// SetOutboundProxy gets a reference to the given NullableString and assigns it to the OutboundProxy field.
func (o *ManagementConfigOutput) SetOutboundProxy(v string) {
	o.OutboundProxy.Set(&v)
}
// SetOutboundProxyNil sets the value for OutboundProxy to be an explicit nil
func (o *ManagementConfigOutput) SetOutboundProxyNil() {
	o.OutboundProxy.Set(nil)
}

// UnsetOutboundProxy ensures that no value is present for OutboundProxy, not even an explicit nil
func (o *ManagementConfigOutput) UnsetOutboundProxy() {
	o.OutboundProxy.Unset()
}

// GetProxies returns the Proxies field value if set, zero value otherwise.
func (o *ManagementConfigOutput) GetProxies() []ManagedProxy {
	if o == nil || IsNil(o.Proxies) {
		var ret []ManagedProxy
		return ret
	}
	return o.Proxies
}

// GetProxiesOk returns a tuple with the Proxies field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ManagementConfigOutput) GetProxiesOk() ([]ManagedProxy, bool) {
	if o == nil || IsNil(o.Proxies) {
		return nil, false
	}
	return o.Proxies, true
}

// HasProxies returns a boolean if a field has been set.
func (o *ManagementConfigOutput) HasProxies() bool {
	if o != nil && !IsNil(o.Proxies) {
		return true
	}

	return false
}

// SetProxies gets a reference to the given []ManagedProxy and assigns it to the Proxies field.
func (o *ManagementConfigOutput) SetProxies(v []ManagedProxy) {
	o.Proxies = v
}

// GetRoutingDefaultOptimize returns the RoutingDefaultOptimize field value if set, zero value otherwise.
func (o *ManagementConfigOutput) GetRoutingDefaultOptimize() string {
	if o == nil || IsNil(o.RoutingDefaultOptimize) {
		var ret string
		return ret
	}
	return *o.RoutingDefaultOptimize
}

// GetRoutingDefaultOptimizeOk returns a tuple with the RoutingDefaultOptimize field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ManagementConfigOutput) GetRoutingDefaultOptimizeOk() (*string, bool) {
	if o == nil || IsNil(o.RoutingDefaultOptimize) {
		return nil, false
	}
	return o.RoutingDefaultOptimize, true
}

// HasRoutingDefaultOptimize returns a boolean if a field has been set.
func (o *ManagementConfigOutput) HasRoutingDefaultOptimize() bool {
	if o != nil && !IsNil(o.RoutingDefaultOptimize) {
		return true
	}

	return false
}

// SetRoutingDefaultOptimize gets a reference to the given string and assigns it to the RoutingDefaultOptimize field.
func (o *ManagementConfigOutput) SetRoutingDefaultOptimize(v string) {
	o.RoutingDefaultOptimize = &v
}

// GetRoutingProfiles returns the RoutingProfiles field value if set, zero value otherwise.
func (o *ManagementConfigOutput) GetRoutingProfiles() map[string]ManagedRoutingProfile {
	if o == nil || IsNil(o.RoutingProfiles) {
		var ret map[string]ManagedRoutingProfile
		return ret
	}
	return o.RoutingProfiles
}

// GetRoutingProfilesOk returns a tuple with the RoutingProfiles field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ManagementConfigOutput) GetRoutingProfilesOk() (map[string]ManagedRoutingProfile, bool) {
	if o == nil || IsNil(o.RoutingProfiles) {
		return map[string]ManagedRoutingProfile{}, false
	}
	return o.RoutingProfiles, true
}

// HasRoutingProfiles returns a boolean if a field has been set.
func (o *ManagementConfigOutput) HasRoutingProfiles() bool {
	if o != nil && !IsNil(o.RoutingProfiles) {
		return true
	}

	return false
}

// SetRoutingProfiles gets a reference to the given map[string]ManagedRoutingProfile and assigns it to the RoutingProfiles field.
func (o *ManagementConfigOutput) SetRoutingProfiles(v map[string]ManagedRoutingProfile) {
	o.RoutingProfiles = v
}

func (o ManagementConfigOutput) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ManagementConfigOutput) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Backends) {
		toSerialize["backends"] = o.Backends
	}
	if !IsNil(o.BudgetAllowUnpriced) {
		toSerialize["budget_allow_unpriced"] = o.BudgetAllowUnpriced
	}
	if !IsNil(o.CatalogModels) {
		toSerialize["catalog_models"] = o.CatalogModels
	}
	if !IsNil(o.Keys) {
		toSerialize["keys"] = o.Keys
	}
	if o.OutboundProxy.IsSet() {
		toSerialize["outbound_proxy"] = o.OutboundProxy.Get()
	}
	if !IsNil(o.Proxies) {
		toSerialize["proxies"] = o.Proxies
	}
	if !IsNil(o.RoutingDefaultOptimize) {
		toSerialize["routing_default_optimize"] = o.RoutingDefaultOptimize
	}
	if !IsNil(o.RoutingProfiles) {
		toSerialize["routing_profiles"] = o.RoutingProfiles
	}
	return toSerialize, nil
}

type NullableManagementConfigOutput struct {
	value *ManagementConfigOutput
	isSet bool
}

func (v NullableManagementConfigOutput) Get() *ManagementConfigOutput {
	return v.value
}

func (v *NullableManagementConfigOutput) Set(val *ManagementConfigOutput) {
	v.value = val
	v.isSet = true
}

func (v NullableManagementConfigOutput) IsSet() bool {
	return v.isSet
}

func (v *NullableManagementConfigOutput) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableManagementConfigOutput(val *ManagementConfigOutput) *NullableManagementConfigOutput {
	return &NullableManagementConfigOutput{value: val, isSet: true}
}

func (v NullableManagementConfigOutput) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableManagementConfigOutput) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


