/*
mm-gateway

Provider-neutral image, video, music, speech and voice cloning gateway.

API version: 0.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package mmgateway

import (
	"encoding/json"
	"time"
	"fmt"
)

// checks if the AudioTaskResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &AudioTaskResponse{}

// AudioTaskResponse struct for AudioTaskResponse
type AudioTaskResponse struct {
	CompletedAt NullableTime `json:"completed_at,omitempty"`
	CreatedAt time.Time `json:"created_at"`
	Error NullableTaskError `json:"error,omitempty"`
	Id string `json:"id"`
	Links ResourceLinks `json:"links"`
	Metadata map[string]interface{} `json:"metadata,omitempty"`
	Model string `json:"model"`
	Object *string `json:"object,omitempty"`
	Outputs []AudioOutput `json:"outputs,omitempty"`
	Routing NullableRoutingInfo `json:"routing,omitempty"`
	Status string `json:"status"`
	Usage NullableUsage `json:"usage,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _AudioTaskResponse AudioTaskResponse

// NewAudioTaskResponse instantiates a new AudioTaskResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAudioTaskResponse(createdAt time.Time, id string, links ResourceLinks, model string, status string) *AudioTaskResponse {
	this := AudioTaskResponse{}
	this.CreatedAt = createdAt
	this.Id = id
	this.Links = links
	this.Model = model
	var object string = "audio"
	this.Object = &object
	this.Status = status
	return &this
}

// NewAudioTaskResponseWithDefaults instantiates a new AudioTaskResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAudioTaskResponseWithDefaults() *AudioTaskResponse {
	this := AudioTaskResponse{}
	var object string = "audio"
	this.Object = &object
	return &this
}

// GetCompletedAt returns the CompletedAt field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *AudioTaskResponse) GetCompletedAt() time.Time {
	if o == nil || IsNil(o.CompletedAt.Get()) {
		var ret time.Time
		return ret
	}
	return *o.CompletedAt.Get()
}

// GetCompletedAtOk returns a tuple with the CompletedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *AudioTaskResponse) GetCompletedAtOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return o.CompletedAt.Get(), o.CompletedAt.IsSet()
}

// HasCompletedAt returns a boolean if a field has been set.
func (o *AudioTaskResponse) HasCompletedAt() bool {
	if o != nil && o.CompletedAt.IsSet() {
		return true
	}

	return false
}

// SetCompletedAt gets a reference to the given NullableTime and assigns it to the CompletedAt field.
func (o *AudioTaskResponse) SetCompletedAt(v time.Time) {
	o.CompletedAt.Set(&v)
}
// SetCompletedAtNil sets the value for CompletedAt to be an explicit nil
func (o *AudioTaskResponse) SetCompletedAtNil() {
	o.CompletedAt.Set(nil)
}

// UnsetCompletedAt ensures that no value is present for CompletedAt, not even an explicit nil
func (o *AudioTaskResponse) UnsetCompletedAt() {
	o.CompletedAt.Unset()
}

// GetCreatedAt returns the CreatedAt field value
func (o *AudioTaskResponse) GetCreatedAt() time.Time {
	if o == nil {
		var ret time.Time
		return ret
	}

	return o.CreatedAt
}

// GetCreatedAtOk returns a tuple with the CreatedAt field value
// and a boolean to check if the value has been set.
func (o *AudioTaskResponse) GetCreatedAtOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return &o.CreatedAt, true
}

// SetCreatedAt sets field value
func (o *AudioTaskResponse) SetCreatedAt(v time.Time) {
	o.CreatedAt = v
}

// GetError returns the Error field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *AudioTaskResponse) GetError() TaskError {
	if o == nil || IsNil(o.Error.Get()) {
		var ret TaskError
		return ret
	}
	return *o.Error.Get()
}

// GetErrorOk returns a tuple with the Error field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *AudioTaskResponse) GetErrorOk() (*TaskError, bool) {
	if o == nil {
		return nil, false
	}
	return o.Error.Get(), o.Error.IsSet()
}

// HasError returns a boolean if a field has been set.
func (o *AudioTaskResponse) HasError() bool {
	if o != nil && o.Error.IsSet() {
		return true
	}

	return false
}

// SetError gets a reference to the given NullableTaskError and assigns it to the Error field.
func (o *AudioTaskResponse) SetError(v TaskError) {
	o.Error.Set(&v)
}
// SetErrorNil sets the value for Error to be an explicit nil
func (o *AudioTaskResponse) SetErrorNil() {
	o.Error.Set(nil)
}

// UnsetError ensures that no value is present for Error, not even an explicit nil
func (o *AudioTaskResponse) UnsetError() {
	o.Error.Unset()
}

// GetId returns the Id field value
func (o *AudioTaskResponse) GetId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *AudioTaskResponse) GetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *AudioTaskResponse) SetId(v string) {
	o.Id = v
}

// GetLinks returns the Links field value
func (o *AudioTaskResponse) GetLinks() ResourceLinks {
	if o == nil {
		var ret ResourceLinks
		return ret
	}

	return o.Links
}

// GetLinksOk returns a tuple with the Links field value
// and a boolean to check if the value has been set.
func (o *AudioTaskResponse) GetLinksOk() (*ResourceLinks, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Links, true
}

// SetLinks sets field value
func (o *AudioTaskResponse) SetLinks(v ResourceLinks) {
	o.Links = v
}

// GetMetadata returns the Metadata field value if set, zero value otherwise.
func (o *AudioTaskResponse) GetMetadata() map[string]interface{} {
	if o == nil || IsNil(o.Metadata) {
		var ret map[string]interface{}
		return ret
	}
	return o.Metadata
}

// GetMetadataOk returns a tuple with the Metadata field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AudioTaskResponse) GetMetadataOk() (map[string]interface{}, bool) {
	if o == nil || IsNil(o.Metadata) {
		return map[string]interface{}{}, false
	}
	return o.Metadata, true
}

// HasMetadata returns a boolean if a field has been set.
func (o *AudioTaskResponse) HasMetadata() bool {
	if o != nil && !IsNil(o.Metadata) {
		return true
	}

	return false
}

// SetMetadata gets a reference to the given map[string]interface{} and assigns it to the Metadata field.
func (o *AudioTaskResponse) SetMetadata(v map[string]interface{}) {
	o.Metadata = v
}

// GetModel returns the Model field value
func (o *AudioTaskResponse) GetModel() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Model
}

// GetModelOk returns a tuple with the Model field value
// and a boolean to check if the value has been set.
func (o *AudioTaskResponse) GetModelOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Model, true
}

// SetModel sets field value
func (o *AudioTaskResponse) SetModel(v string) {
	o.Model = v
}

// GetObject returns the Object field value if set, zero value otherwise.
func (o *AudioTaskResponse) GetObject() string {
	if o == nil || IsNil(o.Object) {
		var ret string
		return ret
	}
	return *o.Object
}

// GetObjectOk returns a tuple with the Object field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AudioTaskResponse) GetObjectOk() (*string, bool) {
	if o == nil || IsNil(o.Object) {
		return nil, false
	}
	return o.Object, true
}

// HasObject returns a boolean if a field has been set.
func (o *AudioTaskResponse) HasObject() bool {
	if o != nil && !IsNil(o.Object) {
		return true
	}

	return false
}

// SetObject gets a reference to the given string and assigns it to the Object field.
func (o *AudioTaskResponse) SetObject(v string) {
	o.Object = &v
}

// GetOutputs returns the Outputs field value if set, zero value otherwise.
func (o *AudioTaskResponse) GetOutputs() []AudioOutput {
	if o == nil || IsNil(o.Outputs) {
		var ret []AudioOutput
		return ret
	}
	return o.Outputs
}

// GetOutputsOk returns a tuple with the Outputs field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AudioTaskResponse) GetOutputsOk() ([]AudioOutput, bool) {
	if o == nil || IsNil(o.Outputs) {
		return nil, false
	}
	return o.Outputs, true
}

// HasOutputs returns a boolean if a field has been set.
func (o *AudioTaskResponse) HasOutputs() bool {
	if o != nil && !IsNil(o.Outputs) {
		return true
	}

	return false
}

// SetOutputs gets a reference to the given []AudioOutput and assigns it to the Outputs field.
func (o *AudioTaskResponse) SetOutputs(v []AudioOutput) {
	o.Outputs = v
}

// GetRouting returns the Routing field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *AudioTaskResponse) GetRouting() RoutingInfo {
	if o == nil || IsNil(o.Routing.Get()) {
		var ret RoutingInfo
		return ret
	}
	return *o.Routing.Get()
}

// GetRoutingOk returns a tuple with the Routing field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *AudioTaskResponse) GetRoutingOk() (*RoutingInfo, bool) {
	if o == nil {
		return nil, false
	}
	return o.Routing.Get(), o.Routing.IsSet()
}

// HasRouting returns a boolean if a field has been set.
func (o *AudioTaskResponse) HasRouting() bool {
	if o != nil && o.Routing.IsSet() {
		return true
	}

	return false
}

// SetRouting gets a reference to the given NullableRoutingInfo and assigns it to the Routing field.
func (o *AudioTaskResponse) SetRouting(v RoutingInfo) {
	o.Routing.Set(&v)
}
// SetRoutingNil sets the value for Routing to be an explicit nil
func (o *AudioTaskResponse) SetRoutingNil() {
	o.Routing.Set(nil)
}

// UnsetRouting ensures that no value is present for Routing, not even an explicit nil
func (o *AudioTaskResponse) UnsetRouting() {
	o.Routing.Unset()
}

// GetStatus returns the Status field value
func (o *AudioTaskResponse) GetStatus() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Status
}

// GetStatusOk returns a tuple with the Status field value
// and a boolean to check if the value has been set.
func (o *AudioTaskResponse) GetStatusOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Status, true
}

// SetStatus sets field value
func (o *AudioTaskResponse) SetStatus(v string) {
	o.Status = v
}

// GetUsage returns the Usage field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *AudioTaskResponse) GetUsage() Usage {
	if o == nil || IsNil(o.Usage.Get()) {
		var ret Usage
		return ret
	}
	return *o.Usage.Get()
}

// GetUsageOk returns a tuple with the Usage field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *AudioTaskResponse) GetUsageOk() (*Usage, bool) {
	if o == nil {
		return nil, false
	}
	return o.Usage.Get(), o.Usage.IsSet()
}

// HasUsage returns a boolean if a field has been set.
func (o *AudioTaskResponse) HasUsage() bool {
	if o != nil && o.Usage.IsSet() {
		return true
	}

	return false
}

// SetUsage gets a reference to the given NullableUsage and assigns it to the Usage field.
func (o *AudioTaskResponse) SetUsage(v Usage) {
	o.Usage.Set(&v)
}
// SetUsageNil sets the value for Usage to be an explicit nil
func (o *AudioTaskResponse) SetUsageNil() {
	o.Usage.Set(nil)
}

// UnsetUsage ensures that no value is present for Usage, not even an explicit nil
func (o *AudioTaskResponse) UnsetUsage() {
	o.Usage.Unset()
}

func (o AudioTaskResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o AudioTaskResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if o.CompletedAt.IsSet() {
		toSerialize["completed_at"] = o.CompletedAt.Get()
	}
	toSerialize["created_at"] = o.CreatedAt
	if o.Error.IsSet() {
		toSerialize["error"] = o.Error.Get()
	}
	toSerialize["id"] = o.Id
	toSerialize["links"] = o.Links
	if !IsNil(o.Metadata) {
		toSerialize["metadata"] = o.Metadata
	}
	toSerialize["model"] = o.Model
	if !IsNil(o.Object) {
		toSerialize["object"] = o.Object
	}
	if !IsNil(o.Outputs) {
		toSerialize["outputs"] = o.Outputs
	}
	if o.Routing.IsSet() {
		toSerialize["routing"] = o.Routing.Get()
	}
	toSerialize["status"] = o.Status
	if o.Usage.IsSet() {
		toSerialize["usage"] = o.Usage.Get()
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *AudioTaskResponse) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"created_at",
		"id",
		"links",
		"model",
		"status",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varAudioTaskResponse := _AudioTaskResponse{}

	err = json.Unmarshal(data, &varAudioTaskResponse)

	if err != nil {
		return err
	}

	*o = AudioTaskResponse(varAudioTaskResponse)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "completed_at")
		delete(additionalProperties, "created_at")
		delete(additionalProperties, "error")
		delete(additionalProperties, "id")
		delete(additionalProperties, "links")
		delete(additionalProperties, "metadata")
		delete(additionalProperties, "model")
		delete(additionalProperties, "object")
		delete(additionalProperties, "outputs")
		delete(additionalProperties, "routing")
		delete(additionalProperties, "status")
		delete(additionalProperties, "usage")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableAudioTaskResponse struct {
	value *AudioTaskResponse
	isSet bool
}

func (v NullableAudioTaskResponse) Get() *AudioTaskResponse {
	return v.value
}

func (v *NullableAudioTaskResponse) Set(val *AudioTaskResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableAudioTaskResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableAudioTaskResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAudioTaskResponse(val *AudioTaskResponse) *NullableAudioTaskResponse {
	return &NullableAudioTaskResponse{value: val, isSet: true}
}

func (v NullableAudioTaskResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAudioTaskResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


