/*
mm-gateway

Provider-neutral image, video, music, speech and voice cloning gateway.

API version: 0.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package mmgateway

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the SelectionHealth type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &SelectionHealth{}

// SelectionHealth struct for SelectionHealth
type SelectionHealth struct {
	Account string `json:"account"`
	Attempts int32 `json:"attempts"`
	Backend string `json:"backend"`
	CooldownRemainingS float32 `json:"cooldown_remaining_s"`
	LatencyS NullableFloat32 `json:"latency_s"`
	Modality string `json:"modality"`
	Model NullableString `json:"model"`
	RateLimited bool `json:"rate_limited"`
	SuccessRate NullableFloat32 `json:"success_rate"`
}

type _SelectionHealth SelectionHealth

// NewSelectionHealth instantiates a new SelectionHealth object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSelectionHealth(account string, attempts int32, backend string, cooldownRemainingS float32, latencyS NullableFloat32, modality string, model NullableString, rateLimited bool, successRate NullableFloat32) *SelectionHealth {
	this := SelectionHealth{}
	this.Account = account
	this.Attempts = attempts
	this.Backend = backend
	this.CooldownRemainingS = cooldownRemainingS
	this.LatencyS = latencyS
	this.Modality = modality
	this.Model = model
	this.RateLimited = rateLimited
	this.SuccessRate = successRate
	return &this
}

// NewSelectionHealthWithDefaults instantiates a new SelectionHealth object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSelectionHealthWithDefaults() *SelectionHealth {
	this := SelectionHealth{}
	return &this
}

// GetAccount returns the Account field value
func (o *SelectionHealth) GetAccount() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Account
}

// GetAccountOk returns a tuple with the Account field value
// and a boolean to check if the value has been set.
func (o *SelectionHealth) GetAccountOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Account, true
}

// SetAccount sets field value
func (o *SelectionHealth) SetAccount(v string) {
	o.Account = v
}

// GetAttempts returns the Attempts field value
func (o *SelectionHealth) GetAttempts() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Attempts
}

// GetAttemptsOk returns a tuple with the Attempts field value
// and a boolean to check if the value has been set.
func (o *SelectionHealth) GetAttemptsOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Attempts, true
}

// SetAttempts sets field value
func (o *SelectionHealth) SetAttempts(v int32) {
	o.Attempts = v
}

// GetBackend returns the Backend field value
func (o *SelectionHealth) GetBackend() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Backend
}

// GetBackendOk returns a tuple with the Backend field value
// and a boolean to check if the value has been set.
func (o *SelectionHealth) GetBackendOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Backend, true
}

// SetBackend sets field value
func (o *SelectionHealth) SetBackend(v string) {
	o.Backend = v
}

// GetCooldownRemainingS returns the CooldownRemainingS field value
func (o *SelectionHealth) GetCooldownRemainingS() float32 {
	if o == nil {
		var ret float32
		return ret
	}

	return o.CooldownRemainingS
}

// GetCooldownRemainingSOk returns a tuple with the CooldownRemainingS field value
// and a boolean to check if the value has been set.
func (o *SelectionHealth) GetCooldownRemainingSOk() (*float32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.CooldownRemainingS, true
}

// SetCooldownRemainingS sets field value
func (o *SelectionHealth) SetCooldownRemainingS(v float32) {
	o.CooldownRemainingS = v
}

// GetLatencyS returns the LatencyS field value
// If the value is explicit nil, the zero value for float32 will be returned
func (o *SelectionHealth) GetLatencyS() float32 {
	if o == nil || o.LatencyS.Get() == nil {
		var ret float32
		return ret
	}

	return *o.LatencyS.Get()
}

// GetLatencySOk returns a tuple with the LatencyS field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *SelectionHealth) GetLatencySOk() (*float32, bool) {
	if o == nil {
		return nil, false
	}
	return o.LatencyS.Get(), o.LatencyS.IsSet()
}

// SetLatencyS sets field value
func (o *SelectionHealth) SetLatencyS(v float32) {
	o.LatencyS.Set(&v)
}

// GetModality returns the Modality field value
func (o *SelectionHealth) GetModality() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Modality
}

// GetModalityOk returns a tuple with the Modality field value
// and a boolean to check if the value has been set.
func (o *SelectionHealth) GetModalityOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Modality, true
}

// SetModality sets field value
func (o *SelectionHealth) SetModality(v string) {
	o.Modality = v
}

// GetModel returns the Model field value
// If the value is explicit nil, the zero value for string will be returned
func (o *SelectionHealth) GetModel() string {
	if o == nil || o.Model.Get() == nil {
		var ret string
		return ret
	}

	return *o.Model.Get()
}

// GetModelOk returns a tuple with the Model field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *SelectionHealth) GetModelOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Model.Get(), o.Model.IsSet()
}

// SetModel sets field value
func (o *SelectionHealth) SetModel(v string) {
	o.Model.Set(&v)
}

// GetRateLimited returns the RateLimited field value
func (o *SelectionHealth) GetRateLimited() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.RateLimited
}

// GetRateLimitedOk returns a tuple with the RateLimited field value
// and a boolean to check if the value has been set.
func (o *SelectionHealth) GetRateLimitedOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.RateLimited, true
}

// SetRateLimited sets field value
func (o *SelectionHealth) SetRateLimited(v bool) {
	o.RateLimited = v
}

// GetSuccessRate returns the SuccessRate field value
// If the value is explicit nil, the zero value for float32 will be returned
func (o *SelectionHealth) GetSuccessRate() float32 {
	if o == nil || o.SuccessRate.Get() == nil {
		var ret float32
		return ret
	}

	return *o.SuccessRate.Get()
}

// GetSuccessRateOk returns a tuple with the SuccessRate field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *SelectionHealth) GetSuccessRateOk() (*float32, bool) {
	if o == nil {
		return nil, false
	}
	return o.SuccessRate.Get(), o.SuccessRate.IsSet()
}

// SetSuccessRate sets field value
func (o *SelectionHealth) SetSuccessRate(v float32) {
	o.SuccessRate.Set(&v)
}

func (o SelectionHealth) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o SelectionHealth) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["account"] = o.Account
	toSerialize["attempts"] = o.Attempts
	toSerialize["backend"] = o.Backend
	toSerialize["cooldown_remaining_s"] = o.CooldownRemainingS
	toSerialize["latency_s"] = o.LatencyS.Get()
	toSerialize["modality"] = o.Modality
	toSerialize["model"] = o.Model.Get()
	toSerialize["rate_limited"] = o.RateLimited
	toSerialize["success_rate"] = o.SuccessRate.Get()
	return toSerialize, nil
}

func (o *SelectionHealth) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"account",
		"attempts",
		"backend",
		"cooldown_remaining_s",
		"latency_s",
		"modality",
		"model",
		"rate_limited",
		"success_rate",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varSelectionHealth := _SelectionHealth{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varSelectionHealth)

	if err != nil {
		return err
	}

	*o = SelectionHealth(varSelectionHealth)

	return err
}

type NullableSelectionHealth struct {
	value *SelectionHealth
	isSet bool
}

func (v NullableSelectionHealth) Get() *SelectionHealth {
	return v.value
}

func (v *NullableSelectionHealth) Set(val *SelectionHealth) {
	v.value = val
	v.isSet = true
}

func (v NullableSelectionHealth) IsSet() bool {
	return v.isSet
}

func (v *NullableSelectionHealth) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSelectionHealth(val *SelectionHealth) *NullableSelectionHealth {
	return &NullableSelectionHealth{value: val, isSet: true}
}

func (v NullableSelectionHealth) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSelectionHealth) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


