/*
mm-gateway

Provider-neutral image, video, music, speech and voice cloning gateway.

API version: 0.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package mmgateway

import (
	"encoding/json"
)

// checks if the MusicParameters type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &MusicParameters{}

// MusicParameters struct for MusicParameters
type MusicParameters struct {
	BitrateKbps NullableInt32 `json:"bitrate_kbps,omitempty"`
	Bpm NullableInt32 `json:"bpm,omitempty"`
	DurationSeconds NullableFloat32 `json:"duration_seconds,omitempty"`
	EnhanceLyrics NullableBool `json:"enhance_lyrics,omitempty"`
	FileFormat NullableString `json:"file_format,omitempty"`
	GuidanceScale NullableFloat32 `json:"guidance_scale,omitempty"`
	InferenceSteps NullableInt32 `json:"inference_steps,omitempty"`
	Instrumental NullableBool `json:"instrumental,omitempty"`
	Key NullableString `json:"key,omitempty"`
	NegativePrompt NullableString `json:"negative_prompt,omitempty"`
	Novelty NullableFloat32 `json:"novelty,omitempty"`
	OutputCount NullableInt32 `json:"output_count,omitempty"`
	Provenance NullableBool `json:"provenance,omitempty"`
	ReferenceAudioStrength NullableFloat32 `json:"reference_audio_strength,omitempty"`
	RespectSectionDurations NullableBool `json:"respect_section_durations,omitempty"`
	SampleRateHz NullableInt32 `json:"sample_rate_hz,omitempty"`
	Scale NullableString `json:"scale,omitempty"`
	Seed NullableInt32 `json:"seed,omitempty"`
	Style NullableString `json:"style,omitempty"`
	StyleStrength NullableFloat32 `json:"style_strength,omitempty"`
	TimeSignature NullableString `json:"time_signature,omitempty"`
	Title NullableString `json:"title,omitempty"`
	VocalGender NullableString `json:"vocal_gender,omitempty"`
	VocalLanguage NullableString `json:"vocal_language,omitempty"`
	Voice NullableString `json:"voice,omitempty"`
}

// NewMusicParameters instantiates a new MusicParameters object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewMusicParameters() *MusicParameters {
	this := MusicParameters{}
	return &this
}

// NewMusicParametersWithDefaults instantiates a new MusicParameters object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewMusicParametersWithDefaults() *MusicParameters {
	this := MusicParameters{}
	return &this
}

// GetBitrateKbps returns the BitrateKbps field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *MusicParameters) GetBitrateKbps() int32 {
	if o == nil || IsNil(o.BitrateKbps.Get()) {
		var ret int32
		return ret
	}
	return *o.BitrateKbps.Get()
}

// GetBitrateKbpsOk returns a tuple with the BitrateKbps field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *MusicParameters) GetBitrateKbpsOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return o.BitrateKbps.Get(), o.BitrateKbps.IsSet()
}

// HasBitrateKbps returns a boolean if a field has been set.
func (o *MusicParameters) HasBitrateKbps() bool {
	if o != nil && o.BitrateKbps.IsSet() {
		return true
	}

	return false
}

// SetBitrateKbps gets a reference to the given NullableInt32 and assigns it to the BitrateKbps field.
func (o *MusicParameters) SetBitrateKbps(v int32) {
	o.BitrateKbps.Set(&v)
}
// SetBitrateKbpsNil sets the value for BitrateKbps to be an explicit nil
func (o *MusicParameters) SetBitrateKbpsNil() {
	o.BitrateKbps.Set(nil)
}

// UnsetBitrateKbps ensures that no value is present for BitrateKbps, not even an explicit nil
func (o *MusicParameters) UnsetBitrateKbps() {
	o.BitrateKbps.Unset()
}

// GetBpm returns the Bpm field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *MusicParameters) GetBpm() int32 {
	if o == nil || IsNil(o.Bpm.Get()) {
		var ret int32
		return ret
	}
	return *o.Bpm.Get()
}

// GetBpmOk returns a tuple with the Bpm field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *MusicParameters) GetBpmOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return o.Bpm.Get(), o.Bpm.IsSet()
}

// HasBpm returns a boolean if a field has been set.
func (o *MusicParameters) HasBpm() bool {
	if o != nil && o.Bpm.IsSet() {
		return true
	}

	return false
}

// SetBpm gets a reference to the given NullableInt32 and assigns it to the Bpm field.
func (o *MusicParameters) SetBpm(v int32) {
	o.Bpm.Set(&v)
}
// SetBpmNil sets the value for Bpm to be an explicit nil
func (o *MusicParameters) SetBpmNil() {
	o.Bpm.Set(nil)
}

// UnsetBpm ensures that no value is present for Bpm, not even an explicit nil
func (o *MusicParameters) UnsetBpm() {
	o.Bpm.Unset()
}

// GetDurationSeconds returns the DurationSeconds field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *MusicParameters) GetDurationSeconds() float32 {
	if o == nil || IsNil(o.DurationSeconds.Get()) {
		var ret float32
		return ret
	}
	return *o.DurationSeconds.Get()
}

// GetDurationSecondsOk returns a tuple with the DurationSeconds field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *MusicParameters) GetDurationSecondsOk() (*float32, bool) {
	if o == nil {
		return nil, false
	}
	return o.DurationSeconds.Get(), o.DurationSeconds.IsSet()
}

// HasDurationSeconds returns a boolean if a field has been set.
func (o *MusicParameters) HasDurationSeconds() bool {
	if o != nil && o.DurationSeconds.IsSet() {
		return true
	}

	return false
}

// SetDurationSeconds gets a reference to the given NullableFloat32 and assigns it to the DurationSeconds field.
func (o *MusicParameters) SetDurationSeconds(v float32) {
	o.DurationSeconds.Set(&v)
}
// SetDurationSecondsNil sets the value for DurationSeconds to be an explicit nil
func (o *MusicParameters) SetDurationSecondsNil() {
	o.DurationSeconds.Set(nil)
}

// UnsetDurationSeconds ensures that no value is present for DurationSeconds, not even an explicit nil
func (o *MusicParameters) UnsetDurationSeconds() {
	o.DurationSeconds.Unset()
}

// GetEnhanceLyrics returns the EnhanceLyrics field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *MusicParameters) GetEnhanceLyrics() bool {
	if o == nil || IsNil(o.EnhanceLyrics.Get()) {
		var ret bool
		return ret
	}
	return *o.EnhanceLyrics.Get()
}

// GetEnhanceLyricsOk returns a tuple with the EnhanceLyrics field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *MusicParameters) GetEnhanceLyricsOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return o.EnhanceLyrics.Get(), o.EnhanceLyrics.IsSet()
}

// HasEnhanceLyrics returns a boolean if a field has been set.
func (o *MusicParameters) HasEnhanceLyrics() bool {
	if o != nil && o.EnhanceLyrics.IsSet() {
		return true
	}

	return false
}

// SetEnhanceLyrics gets a reference to the given NullableBool and assigns it to the EnhanceLyrics field.
func (o *MusicParameters) SetEnhanceLyrics(v bool) {
	o.EnhanceLyrics.Set(&v)
}
// SetEnhanceLyricsNil sets the value for EnhanceLyrics to be an explicit nil
func (o *MusicParameters) SetEnhanceLyricsNil() {
	o.EnhanceLyrics.Set(nil)
}

// UnsetEnhanceLyrics ensures that no value is present for EnhanceLyrics, not even an explicit nil
func (o *MusicParameters) UnsetEnhanceLyrics() {
	o.EnhanceLyrics.Unset()
}

// GetFileFormat returns the FileFormat field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *MusicParameters) GetFileFormat() string {
	if o == nil || IsNil(o.FileFormat.Get()) {
		var ret string
		return ret
	}
	return *o.FileFormat.Get()
}

// GetFileFormatOk returns a tuple with the FileFormat field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *MusicParameters) GetFileFormatOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.FileFormat.Get(), o.FileFormat.IsSet()
}

// HasFileFormat returns a boolean if a field has been set.
func (o *MusicParameters) HasFileFormat() bool {
	if o != nil && o.FileFormat.IsSet() {
		return true
	}

	return false
}

// SetFileFormat gets a reference to the given NullableString and assigns it to the FileFormat field.
func (o *MusicParameters) SetFileFormat(v string) {
	o.FileFormat.Set(&v)
}
// SetFileFormatNil sets the value for FileFormat to be an explicit nil
func (o *MusicParameters) SetFileFormatNil() {
	o.FileFormat.Set(nil)
}

// UnsetFileFormat ensures that no value is present for FileFormat, not even an explicit nil
func (o *MusicParameters) UnsetFileFormat() {
	o.FileFormat.Unset()
}

// GetGuidanceScale returns the GuidanceScale field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *MusicParameters) GetGuidanceScale() float32 {
	if o == nil || IsNil(o.GuidanceScale.Get()) {
		var ret float32
		return ret
	}
	return *o.GuidanceScale.Get()
}

// GetGuidanceScaleOk returns a tuple with the GuidanceScale field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *MusicParameters) GetGuidanceScaleOk() (*float32, bool) {
	if o == nil {
		return nil, false
	}
	return o.GuidanceScale.Get(), o.GuidanceScale.IsSet()
}

// HasGuidanceScale returns a boolean if a field has been set.
func (o *MusicParameters) HasGuidanceScale() bool {
	if o != nil && o.GuidanceScale.IsSet() {
		return true
	}

	return false
}

// SetGuidanceScale gets a reference to the given NullableFloat32 and assigns it to the GuidanceScale field.
func (o *MusicParameters) SetGuidanceScale(v float32) {
	o.GuidanceScale.Set(&v)
}
// SetGuidanceScaleNil sets the value for GuidanceScale to be an explicit nil
func (o *MusicParameters) SetGuidanceScaleNil() {
	o.GuidanceScale.Set(nil)
}

// UnsetGuidanceScale ensures that no value is present for GuidanceScale, not even an explicit nil
func (o *MusicParameters) UnsetGuidanceScale() {
	o.GuidanceScale.Unset()
}

// GetInferenceSteps returns the InferenceSteps field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *MusicParameters) GetInferenceSteps() int32 {
	if o == nil || IsNil(o.InferenceSteps.Get()) {
		var ret int32
		return ret
	}
	return *o.InferenceSteps.Get()
}

// GetInferenceStepsOk returns a tuple with the InferenceSteps field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *MusicParameters) GetInferenceStepsOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return o.InferenceSteps.Get(), o.InferenceSteps.IsSet()
}

// HasInferenceSteps returns a boolean if a field has been set.
func (o *MusicParameters) HasInferenceSteps() bool {
	if o != nil && o.InferenceSteps.IsSet() {
		return true
	}

	return false
}

// SetInferenceSteps gets a reference to the given NullableInt32 and assigns it to the InferenceSteps field.
func (o *MusicParameters) SetInferenceSteps(v int32) {
	o.InferenceSteps.Set(&v)
}
// SetInferenceStepsNil sets the value for InferenceSteps to be an explicit nil
func (o *MusicParameters) SetInferenceStepsNil() {
	o.InferenceSteps.Set(nil)
}

// UnsetInferenceSteps ensures that no value is present for InferenceSteps, not even an explicit nil
func (o *MusicParameters) UnsetInferenceSteps() {
	o.InferenceSteps.Unset()
}

// GetInstrumental returns the Instrumental field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *MusicParameters) GetInstrumental() bool {
	if o == nil || IsNil(o.Instrumental.Get()) {
		var ret bool
		return ret
	}
	return *o.Instrumental.Get()
}

// GetInstrumentalOk returns a tuple with the Instrumental field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *MusicParameters) GetInstrumentalOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return o.Instrumental.Get(), o.Instrumental.IsSet()
}

// HasInstrumental returns a boolean if a field has been set.
func (o *MusicParameters) HasInstrumental() bool {
	if o != nil && o.Instrumental.IsSet() {
		return true
	}

	return false
}

// SetInstrumental gets a reference to the given NullableBool and assigns it to the Instrumental field.
func (o *MusicParameters) SetInstrumental(v bool) {
	o.Instrumental.Set(&v)
}
// SetInstrumentalNil sets the value for Instrumental to be an explicit nil
func (o *MusicParameters) SetInstrumentalNil() {
	o.Instrumental.Set(nil)
}

// UnsetInstrumental ensures that no value is present for Instrumental, not even an explicit nil
func (o *MusicParameters) UnsetInstrumental() {
	o.Instrumental.Unset()
}

// GetKey returns the Key field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *MusicParameters) GetKey() string {
	if o == nil || IsNil(o.Key.Get()) {
		var ret string
		return ret
	}
	return *o.Key.Get()
}

// GetKeyOk returns a tuple with the Key field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *MusicParameters) GetKeyOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Key.Get(), o.Key.IsSet()
}

// HasKey returns a boolean if a field has been set.
func (o *MusicParameters) HasKey() bool {
	if o != nil && o.Key.IsSet() {
		return true
	}

	return false
}

// SetKey gets a reference to the given NullableString and assigns it to the Key field.
func (o *MusicParameters) SetKey(v string) {
	o.Key.Set(&v)
}
// SetKeyNil sets the value for Key to be an explicit nil
func (o *MusicParameters) SetKeyNil() {
	o.Key.Set(nil)
}

// UnsetKey ensures that no value is present for Key, not even an explicit nil
func (o *MusicParameters) UnsetKey() {
	o.Key.Unset()
}

// GetNegativePrompt returns the NegativePrompt field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *MusicParameters) GetNegativePrompt() string {
	if o == nil || IsNil(o.NegativePrompt.Get()) {
		var ret string
		return ret
	}
	return *o.NegativePrompt.Get()
}

// GetNegativePromptOk returns a tuple with the NegativePrompt field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *MusicParameters) GetNegativePromptOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.NegativePrompt.Get(), o.NegativePrompt.IsSet()
}

// HasNegativePrompt returns a boolean if a field has been set.
func (o *MusicParameters) HasNegativePrompt() bool {
	if o != nil && o.NegativePrompt.IsSet() {
		return true
	}

	return false
}

// SetNegativePrompt gets a reference to the given NullableString and assigns it to the NegativePrompt field.
func (o *MusicParameters) SetNegativePrompt(v string) {
	o.NegativePrompt.Set(&v)
}
// SetNegativePromptNil sets the value for NegativePrompt to be an explicit nil
func (o *MusicParameters) SetNegativePromptNil() {
	o.NegativePrompt.Set(nil)
}

// UnsetNegativePrompt ensures that no value is present for NegativePrompt, not even an explicit nil
func (o *MusicParameters) UnsetNegativePrompt() {
	o.NegativePrompt.Unset()
}

// GetNovelty returns the Novelty field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *MusicParameters) GetNovelty() float32 {
	if o == nil || IsNil(o.Novelty.Get()) {
		var ret float32
		return ret
	}
	return *o.Novelty.Get()
}

// GetNoveltyOk returns a tuple with the Novelty field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *MusicParameters) GetNoveltyOk() (*float32, bool) {
	if o == nil {
		return nil, false
	}
	return o.Novelty.Get(), o.Novelty.IsSet()
}

// HasNovelty returns a boolean if a field has been set.
func (o *MusicParameters) HasNovelty() bool {
	if o != nil && o.Novelty.IsSet() {
		return true
	}

	return false
}

// SetNovelty gets a reference to the given NullableFloat32 and assigns it to the Novelty field.
func (o *MusicParameters) SetNovelty(v float32) {
	o.Novelty.Set(&v)
}
// SetNoveltyNil sets the value for Novelty to be an explicit nil
func (o *MusicParameters) SetNoveltyNil() {
	o.Novelty.Set(nil)
}

// UnsetNovelty ensures that no value is present for Novelty, not even an explicit nil
func (o *MusicParameters) UnsetNovelty() {
	o.Novelty.Unset()
}

// GetOutputCount returns the OutputCount field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *MusicParameters) GetOutputCount() int32 {
	if o == nil || IsNil(o.OutputCount.Get()) {
		var ret int32
		return ret
	}
	return *o.OutputCount.Get()
}

// GetOutputCountOk returns a tuple with the OutputCount field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *MusicParameters) GetOutputCountOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return o.OutputCount.Get(), o.OutputCount.IsSet()
}

// HasOutputCount returns a boolean if a field has been set.
func (o *MusicParameters) HasOutputCount() bool {
	if o != nil && o.OutputCount.IsSet() {
		return true
	}

	return false
}

// SetOutputCount gets a reference to the given NullableInt32 and assigns it to the OutputCount field.
func (o *MusicParameters) SetOutputCount(v int32) {
	o.OutputCount.Set(&v)
}
// SetOutputCountNil sets the value for OutputCount to be an explicit nil
func (o *MusicParameters) SetOutputCountNil() {
	o.OutputCount.Set(nil)
}

// UnsetOutputCount ensures that no value is present for OutputCount, not even an explicit nil
func (o *MusicParameters) UnsetOutputCount() {
	o.OutputCount.Unset()
}

// GetProvenance returns the Provenance field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *MusicParameters) GetProvenance() bool {
	if o == nil || IsNil(o.Provenance.Get()) {
		var ret bool
		return ret
	}
	return *o.Provenance.Get()
}

// GetProvenanceOk returns a tuple with the Provenance field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *MusicParameters) GetProvenanceOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return o.Provenance.Get(), o.Provenance.IsSet()
}

// HasProvenance returns a boolean if a field has been set.
func (o *MusicParameters) HasProvenance() bool {
	if o != nil && o.Provenance.IsSet() {
		return true
	}

	return false
}

// SetProvenance gets a reference to the given NullableBool and assigns it to the Provenance field.
func (o *MusicParameters) SetProvenance(v bool) {
	o.Provenance.Set(&v)
}
// SetProvenanceNil sets the value for Provenance to be an explicit nil
func (o *MusicParameters) SetProvenanceNil() {
	o.Provenance.Set(nil)
}

// UnsetProvenance ensures that no value is present for Provenance, not even an explicit nil
func (o *MusicParameters) UnsetProvenance() {
	o.Provenance.Unset()
}

// GetReferenceAudioStrength returns the ReferenceAudioStrength field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *MusicParameters) GetReferenceAudioStrength() float32 {
	if o == nil || IsNil(o.ReferenceAudioStrength.Get()) {
		var ret float32
		return ret
	}
	return *o.ReferenceAudioStrength.Get()
}

// GetReferenceAudioStrengthOk returns a tuple with the ReferenceAudioStrength field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *MusicParameters) GetReferenceAudioStrengthOk() (*float32, bool) {
	if o == nil {
		return nil, false
	}
	return o.ReferenceAudioStrength.Get(), o.ReferenceAudioStrength.IsSet()
}

// HasReferenceAudioStrength returns a boolean if a field has been set.
func (o *MusicParameters) HasReferenceAudioStrength() bool {
	if o != nil && o.ReferenceAudioStrength.IsSet() {
		return true
	}

	return false
}

// SetReferenceAudioStrength gets a reference to the given NullableFloat32 and assigns it to the ReferenceAudioStrength field.
func (o *MusicParameters) SetReferenceAudioStrength(v float32) {
	o.ReferenceAudioStrength.Set(&v)
}
// SetReferenceAudioStrengthNil sets the value for ReferenceAudioStrength to be an explicit nil
func (o *MusicParameters) SetReferenceAudioStrengthNil() {
	o.ReferenceAudioStrength.Set(nil)
}

// UnsetReferenceAudioStrength ensures that no value is present for ReferenceAudioStrength, not even an explicit nil
func (o *MusicParameters) UnsetReferenceAudioStrength() {
	o.ReferenceAudioStrength.Unset()
}

// GetRespectSectionDurations returns the RespectSectionDurations field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *MusicParameters) GetRespectSectionDurations() bool {
	if o == nil || IsNil(o.RespectSectionDurations.Get()) {
		var ret bool
		return ret
	}
	return *o.RespectSectionDurations.Get()
}

// GetRespectSectionDurationsOk returns a tuple with the RespectSectionDurations field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *MusicParameters) GetRespectSectionDurationsOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return o.RespectSectionDurations.Get(), o.RespectSectionDurations.IsSet()
}

// HasRespectSectionDurations returns a boolean if a field has been set.
func (o *MusicParameters) HasRespectSectionDurations() bool {
	if o != nil && o.RespectSectionDurations.IsSet() {
		return true
	}

	return false
}

// SetRespectSectionDurations gets a reference to the given NullableBool and assigns it to the RespectSectionDurations field.
func (o *MusicParameters) SetRespectSectionDurations(v bool) {
	o.RespectSectionDurations.Set(&v)
}
// SetRespectSectionDurationsNil sets the value for RespectSectionDurations to be an explicit nil
func (o *MusicParameters) SetRespectSectionDurationsNil() {
	o.RespectSectionDurations.Set(nil)
}

// UnsetRespectSectionDurations ensures that no value is present for RespectSectionDurations, not even an explicit nil
func (o *MusicParameters) UnsetRespectSectionDurations() {
	o.RespectSectionDurations.Unset()
}

// GetSampleRateHz returns the SampleRateHz field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *MusicParameters) GetSampleRateHz() int32 {
	if o == nil || IsNil(o.SampleRateHz.Get()) {
		var ret int32
		return ret
	}
	return *o.SampleRateHz.Get()
}

// GetSampleRateHzOk returns a tuple with the SampleRateHz field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *MusicParameters) GetSampleRateHzOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return o.SampleRateHz.Get(), o.SampleRateHz.IsSet()
}

// HasSampleRateHz returns a boolean if a field has been set.
func (o *MusicParameters) HasSampleRateHz() bool {
	if o != nil && o.SampleRateHz.IsSet() {
		return true
	}

	return false
}

// SetSampleRateHz gets a reference to the given NullableInt32 and assigns it to the SampleRateHz field.
func (o *MusicParameters) SetSampleRateHz(v int32) {
	o.SampleRateHz.Set(&v)
}
// SetSampleRateHzNil sets the value for SampleRateHz to be an explicit nil
func (o *MusicParameters) SetSampleRateHzNil() {
	o.SampleRateHz.Set(nil)
}

// UnsetSampleRateHz ensures that no value is present for SampleRateHz, not even an explicit nil
func (o *MusicParameters) UnsetSampleRateHz() {
	o.SampleRateHz.Unset()
}

// GetScale returns the Scale field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *MusicParameters) GetScale() string {
	if o == nil || IsNil(o.Scale.Get()) {
		var ret string
		return ret
	}
	return *o.Scale.Get()
}

// GetScaleOk returns a tuple with the Scale field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *MusicParameters) GetScaleOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Scale.Get(), o.Scale.IsSet()
}

// HasScale returns a boolean if a field has been set.
func (o *MusicParameters) HasScale() bool {
	if o != nil && o.Scale.IsSet() {
		return true
	}

	return false
}

// SetScale gets a reference to the given NullableString and assigns it to the Scale field.
func (o *MusicParameters) SetScale(v string) {
	o.Scale.Set(&v)
}
// SetScaleNil sets the value for Scale to be an explicit nil
func (o *MusicParameters) SetScaleNil() {
	o.Scale.Set(nil)
}

// UnsetScale ensures that no value is present for Scale, not even an explicit nil
func (o *MusicParameters) UnsetScale() {
	o.Scale.Unset()
}

// GetSeed returns the Seed field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *MusicParameters) GetSeed() int32 {
	if o == nil || IsNil(o.Seed.Get()) {
		var ret int32
		return ret
	}
	return *o.Seed.Get()
}

// GetSeedOk returns a tuple with the Seed field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *MusicParameters) GetSeedOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return o.Seed.Get(), o.Seed.IsSet()
}

// HasSeed returns a boolean if a field has been set.
func (o *MusicParameters) HasSeed() bool {
	if o != nil && o.Seed.IsSet() {
		return true
	}

	return false
}

// SetSeed gets a reference to the given NullableInt32 and assigns it to the Seed field.
func (o *MusicParameters) SetSeed(v int32) {
	o.Seed.Set(&v)
}
// SetSeedNil sets the value for Seed to be an explicit nil
func (o *MusicParameters) SetSeedNil() {
	o.Seed.Set(nil)
}

// UnsetSeed ensures that no value is present for Seed, not even an explicit nil
func (o *MusicParameters) UnsetSeed() {
	o.Seed.Unset()
}

// GetStyle returns the Style field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *MusicParameters) GetStyle() string {
	if o == nil || IsNil(o.Style.Get()) {
		var ret string
		return ret
	}
	return *o.Style.Get()
}

// GetStyleOk returns a tuple with the Style field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *MusicParameters) GetStyleOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Style.Get(), o.Style.IsSet()
}

// HasStyle returns a boolean if a field has been set.
func (o *MusicParameters) HasStyle() bool {
	if o != nil && o.Style.IsSet() {
		return true
	}

	return false
}

// SetStyle gets a reference to the given NullableString and assigns it to the Style field.
func (o *MusicParameters) SetStyle(v string) {
	o.Style.Set(&v)
}
// SetStyleNil sets the value for Style to be an explicit nil
func (o *MusicParameters) SetStyleNil() {
	o.Style.Set(nil)
}

// UnsetStyle ensures that no value is present for Style, not even an explicit nil
func (o *MusicParameters) UnsetStyle() {
	o.Style.Unset()
}

// GetStyleStrength returns the StyleStrength field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *MusicParameters) GetStyleStrength() float32 {
	if o == nil || IsNil(o.StyleStrength.Get()) {
		var ret float32
		return ret
	}
	return *o.StyleStrength.Get()
}

// GetStyleStrengthOk returns a tuple with the StyleStrength field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *MusicParameters) GetStyleStrengthOk() (*float32, bool) {
	if o == nil {
		return nil, false
	}
	return o.StyleStrength.Get(), o.StyleStrength.IsSet()
}

// HasStyleStrength returns a boolean if a field has been set.
func (o *MusicParameters) HasStyleStrength() bool {
	if o != nil && o.StyleStrength.IsSet() {
		return true
	}

	return false
}

// SetStyleStrength gets a reference to the given NullableFloat32 and assigns it to the StyleStrength field.
func (o *MusicParameters) SetStyleStrength(v float32) {
	o.StyleStrength.Set(&v)
}
// SetStyleStrengthNil sets the value for StyleStrength to be an explicit nil
func (o *MusicParameters) SetStyleStrengthNil() {
	o.StyleStrength.Set(nil)
}

// UnsetStyleStrength ensures that no value is present for StyleStrength, not even an explicit nil
func (o *MusicParameters) UnsetStyleStrength() {
	o.StyleStrength.Unset()
}

// GetTimeSignature returns the TimeSignature field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *MusicParameters) GetTimeSignature() string {
	if o == nil || IsNil(o.TimeSignature.Get()) {
		var ret string
		return ret
	}
	return *o.TimeSignature.Get()
}

// GetTimeSignatureOk returns a tuple with the TimeSignature field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *MusicParameters) GetTimeSignatureOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.TimeSignature.Get(), o.TimeSignature.IsSet()
}

// HasTimeSignature returns a boolean if a field has been set.
func (o *MusicParameters) HasTimeSignature() bool {
	if o != nil && o.TimeSignature.IsSet() {
		return true
	}

	return false
}

// SetTimeSignature gets a reference to the given NullableString and assigns it to the TimeSignature field.
func (o *MusicParameters) SetTimeSignature(v string) {
	o.TimeSignature.Set(&v)
}
// SetTimeSignatureNil sets the value for TimeSignature to be an explicit nil
func (o *MusicParameters) SetTimeSignatureNil() {
	o.TimeSignature.Set(nil)
}

// UnsetTimeSignature ensures that no value is present for TimeSignature, not even an explicit nil
func (o *MusicParameters) UnsetTimeSignature() {
	o.TimeSignature.Unset()
}

// GetTitle returns the Title field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *MusicParameters) GetTitle() string {
	if o == nil || IsNil(o.Title.Get()) {
		var ret string
		return ret
	}
	return *o.Title.Get()
}

// GetTitleOk returns a tuple with the Title field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *MusicParameters) GetTitleOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Title.Get(), o.Title.IsSet()
}

// HasTitle returns a boolean if a field has been set.
func (o *MusicParameters) HasTitle() bool {
	if o != nil && o.Title.IsSet() {
		return true
	}

	return false
}

// SetTitle gets a reference to the given NullableString and assigns it to the Title field.
func (o *MusicParameters) SetTitle(v string) {
	o.Title.Set(&v)
}
// SetTitleNil sets the value for Title to be an explicit nil
func (o *MusicParameters) SetTitleNil() {
	o.Title.Set(nil)
}

// UnsetTitle ensures that no value is present for Title, not even an explicit nil
func (o *MusicParameters) UnsetTitle() {
	o.Title.Unset()
}

// GetVocalGender returns the VocalGender field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *MusicParameters) GetVocalGender() string {
	if o == nil || IsNil(o.VocalGender.Get()) {
		var ret string
		return ret
	}
	return *o.VocalGender.Get()
}

// GetVocalGenderOk returns a tuple with the VocalGender field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *MusicParameters) GetVocalGenderOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.VocalGender.Get(), o.VocalGender.IsSet()
}

// HasVocalGender returns a boolean if a field has been set.
func (o *MusicParameters) HasVocalGender() bool {
	if o != nil && o.VocalGender.IsSet() {
		return true
	}

	return false
}

// SetVocalGender gets a reference to the given NullableString and assigns it to the VocalGender field.
func (o *MusicParameters) SetVocalGender(v string) {
	o.VocalGender.Set(&v)
}
// SetVocalGenderNil sets the value for VocalGender to be an explicit nil
func (o *MusicParameters) SetVocalGenderNil() {
	o.VocalGender.Set(nil)
}

// UnsetVocalGender ensures that no value is present for VocalGender, not even an explicit nil
func (o *MusicParameters) UnsetVocalGender() {
	o.VocalGender.Unset()
}

// GetVocalLanguage returns the VocalLanguage field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *MusicParameters) GetVocalLanguage() string {
	if o == nil || IsNil(o.VocalLanguage.Get()) {
		var ret string
		return ret
	}
	return *o.VocalLanguage.Get()
}

// GetVocalLanguageOk returns a tuple with the VocalLanguage field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *MusicParameters) GetVocalLanguageOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.VocalLanguage.Get(), o.VocalLanguage.IsSet()
}

// HasVocalLanguage returns a boolean if a field has been set.
func (o *MusicParameters) HasVocalLanguage() bool {
	if o != nil && o.VocalLanguage.IsSet() {
		return true
	}

	return false
}

// SetVocalLanguage gets a reference to the given NullableString and assigns it to the VocalLanguage field.
func (o *MusicParameters) SetVocalLanguage(v string) {
	o.VocalLanguage.Set(&v)
}
// SetVocalLanguageNil sets the value for VocalLanguage to be an explicit nil
func (o *MusicParameters) SetVocalLanguageNil() {
	o.VocalLanguage.Set(nil)
}

// UnsetVocalLanguage ensures that no value is present for VocalLanguage, not even an explicit nil
func (o *MusicParameters) UnsetVocalLanguage() {
	o.VocalLanguage.Unset()
}

// GetVoice returns the Voice field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *MusicParameters) GetVoice() string {
	if o == nil || IsNil(o.Voice.Get()) {
		var ret string
		return ret
	}
	return *o.Voice.Get()
}

// GetVoiceOk returns a tuple with the Voice field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *MusicParameters) GetVoiceOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Voice.Get(), o.Voice.IsSet()
}

// HasVoice returns a boolean if a field has been set.
func (o *MusicParameters) HasVoice() bool {
	if o != nil && o.Voice.IsSet() {
		return true
	}

	return false
}

// SetVoice gets a reference to the given NullableString and assigns it to the Voice field.
func (o *MusicParameters) SetVoice(v string) {
	o.Voice.Set(&v)
}
// SetVoiceNil sets the value for Voice to be an explicit nil
func (o *MusicParameters) SetVoiceNil() {
	o.Voice.Set(nil)
}

// UnsetVoice ensures that no value is present for Voice, not even an explicit nil
func (o *MusicParameters) UnsetVoice() {
	o.Voice.Unset()
}

func (o MusicParameters) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o MusicParameters) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if o.BitrateKbps.IsSet() {
		toSerialize["bitrate_kbps"] = o.BitrateKbps.Get()
	}
	if o.Bpm.IsSet() {
		toSerialize["bpm"] = o.Bpm.Get()
	}
	if o.DurationSeconds.IsSet() {
		toSerialize["duration_seconds"] = o.DurationSeconds.Get()
	}
	if o.EnhanceLyrics.IsSet() {
		toSerialize["enhance_lyrics"] = o.EnhanceLyrics.Get()
	}
	if o.FileFormat.IsSet() {
		toSerialize["file_format"] = o.FileFormat.Get()
	}
	if o.GuidanceScale.IsSet() {
		toSerialize["guidance_scale"] = o.GuidanceScale.Get()
	}
	if o.InferenceSteps.IsSet() {
		toSerialize["inference_steps"] = o.InferenceSteps.Get()
	}
	if o.Instrumental.IsSet() {
		toSerialize["instrumental"] = o.Instrumental.Get()
	}
	if o.Key.IsSet() {
		toSerialize["key"] = o.Key.Get()
	}
	if o.NegativePrompt.IsSet() {
		toSerialize["negative_prompt"] = o.NegativePrompt.Get()
	}
	if o.Novelty.IsSet() {
		toSerialize["novelty"] = o.Novelty.Get()
	}
	if o.OutputCount.IsSet() {
		toSerialize["output_count"] = o.OutputCount.Get()
	}
	if o.Provenance.IsSet() {
		toSerialize["provenance"] = o.Provenance.Get()
	}
	if o.ReferenceAudioStrength.IsSet() {
		toSerialize["reference_audio_strength"] = o.ReferenceAudioStrength.Get()
	}
	if o.RespectSectionDurations.IsSet() {
		toSerialize["respect_section_durations"] = o.RespectSectionDurations.Get()
	}
	if o.SampleRateHz.IsSet() {
		toSerialize["sample_rate_hz"] = o.SampleRateHz.Get()
	}
	if o.Scale.IsSet() {
		toSerialize["scale"] = o.Scale.Get()
	}
	if o.Seed.IsSet() {
		toSerialize["seed"] = o.Seed.Get()
	}
	if o.Style.IsSet() {
		toSerialize["style"] = o.Style.Get()
	}
	if o.StyleStrength.IsSet() {
		toSerialize["style_strength"] = o.StyleStrength.Get()
	}
	if o.TimeSignature.IsSet() {
		toSerialize["time_signature"] = o.TimeSignature.Get()
	}
	if o.Title.IsSet() {
		toSerialize["title"] = o.Title.Get()
	}
	if o.VocalGender.IsSet() {
		toSerialize["vocal_gender"] = o.VocalGender.Get()
	}
	if o.VocalLanguage.IsSet() {
		toSerialize["vocal_language"] = o.VocalLanguage.Get()
	}
	if o.Voice.IsSet() {
		toSerialize["voice"] = o.Voice.Get()
	}
	return toSerialize, nil
}

type NullableMusicParameters struct {
	value *MusicParameters
	isSet bool
}

func (v NullableMusicParameters) Get() *MusicParameters {
	return v.value
}

func (v *NullableMusicParameters) Set(val *MusicParameters) {
	v.value = val
	v.isSet = true
}

func (v NullableMusicParameters) IsSet() bool {
	return v.isSet
}

func (v *NullableMusicParameters) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableMusicParameters(val *MusicParameters) *NullableMusicParameters {
	return &NullableMusicParameters{value: val, isSet: true}
}

func (v NullableMusicParameters) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableMusicParameters) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


