/*
mm-gateway

Unified image, video, and music gateway with separate REST APIs.

API version: 0.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package mmgateway

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the VideoAudioInput type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &VideoAudioInput{}

// VideoAudioInput struct for VideoAudioInput
type VideoAudioInput struct {
	Role *string `json:"role,omitempty"`
	Type string `json:"type"`
	// Absolute media URI. Inline media uses a base64 data URI.
	Uri string `json:"uri"`
}

type _VideoAudioInput VideoAudioInput

// NewVideoAudioInput instantiates a new VideoAudioInput object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewVideoAudioInput(type_ string, uri string) *VideoAudioInput {
	this := VideoAudioInput{}
	var role string = "reference_audio"
	this.Role = &role
	this.Type = type_
	this.Uri = uri
	return &this
}

// NewVideoAudioInputWithDefaults instantiates a new VideoAudioInput object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewVideoAudioInputWithDefaults() *VideoAudioInput {
	this := VideoAudioInput{}
	var role string = "reference_audio"
	this.Role = &role
	return &this
}

// GetRole returns the Role field value if set, zero value otherwise.
func (o *VideoAudioInput) GetRole() string {
	if o == nil || IsNil(o.Role) {
		var ret string
		return ret
	}
	return *o.Role
}

// GetRoleOk returns a tuple with the Role field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *VideoAudioInput) GetRoleOk() (*string, bool) {
	if o == nil || IsNil(o.Role) {
		return nil, false
	}
	return o.Role, true
}

// HasRole returns a boolean if a field has been set.
func (o *VideoAudioInput) HasRole() bool {
	if o != nil && !IsNil(o.Role) {
		return true
	}

	return false
}

// SetRole gets a reference to the given string and assigns it to the Role field.
func (o *VideoAudioInput) SetRole(v string) {
	o.Role = &v
}

// GetType returns the Type field value
func (o *VideoAudioInput) GetType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Type
}

// GetTypeOk returns a tuple with the Type field value
// and a boolean to check if the value has been set.
func (o *VideoAudioInput) GetTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Type, true
}

// SetType sets field value
func (o *VideoAudioInput) SetType(v string) {
	o.Type = v
}

// GetUri returns the Uri field value
func (o *VideoAudioInput) GetUri() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Uri
}

// GetUriOk returns a tuple with the Uri field value
// and a boolean to check if the value has been set.
func (o *VideoAudioInput) GetUriOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Uri, true
}

// SetUri sets field value
func (o *VideoAudioInput) SetUri(v string) {
	o.Uri = v
}

func (o VideoAudioInput) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o VideoAudioInput) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Role) {
		toSerialize["role"] = o.Role
	}
	toSerialize["type"] = o.Type
	toSerialize["uri"] = o.Uri
	return toSerialize, nil
}

func (o *VideoAudioInput) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"type",
		"uri",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varVideoAudioInput := _VideoAudioInput{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varVideoAudioInput)

	if err != nil {
		return err
	}

	*o = VideoAudioInput(varVideoAudioInput)

	return err
}

type NullableVideoAudioInput struct {
	value *VideoAudioInput
	isSet bool
}

func (v NullableVideoAudioInput) Get() *VideoAudioInput {
	return v.value
}

func (v *NullableVideoAudioInput) Set(val *VideoAudioInput) {
	v.value = val
	v.isSet = true
}

func (v NullableVideoAudioInput) IsSet() bool {
	return v.isSet
}

func (v *NullableVideoAudioInput) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableVideoAudioInput(val *VideoAudioInput) *NullableVideoAudioInput {
	return &NullableVideoAudioInput{value: val, isSet: true}
}

func (v NullableVideoAudioInput) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableVideoAudioInput) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


