/*
mm-gateway

Provider-neutral image, video, music, speech and voice cloning gateway.

API version: 0.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package mmgateway

import (
	"encoding/json"
	"fmt"
)

// checks if the ModelListResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ModelListResponse{}

// ModelListResponse struct for ModelListResponse
type ModelListResponse struct {
	Data []ModelEntry `json:"data"`
	Object *string `json:"object,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _ModelListResponse ModelListResponse

// NewModelListResponse instantiates a new ModelListResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewModelListResponse(data []ModelEntry) *ModelListResponse {
	this := ModelListResponse{}
	this.Data = data
	var object string = "list"
	this.Object = &object
	return &this
}

// NewModelListResponseWithDefaults instantiates a new ModelListResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewModelListResponseWithDefaults() *ModelListResponse {
	this := ModelListResponse{}
	var object string = "list"
	this.Object = &object
	return &this
}

// GetData returns the Data field value
func (o *ModelListResponse) GetData() []ModelEntry {
	if o == nil {
		var ret []ModelEntry
		return ret
	}

	return o.Data
}

// GetDataOk returns a tuple with the Data field value
// and a boolean to check if the value has been set.
func (o *ModelListResponse) GetDataOk() ([]ModelEntry, bool) {
	if o == nil {
		return nil, false
	}
	return o.Data, true
}

// SetData sets field value
func (o *ModelListResponse) SetData(v []ModelEntry) {
	o.Data = v
}

// GetObject returns the Object field value if set, zero value otherwise.
func (o *ModelListResponse) GetObject() string {
	if o == nil || IsNil(o.Object) {
		var ret string
		return ret
	}
	return *o.Object
}

// GetObjectOk returns a tuple with the Object field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ModelListResponse) GetObjectOk() (*string, bool) {
	if o == nil || IsNil(o.Object) {
		return nil, false
	}
	return o.Object, true
}

// HasObject returns a boolean if a field has been set.
func (o *ModelListResponse) HasObject() bool {
	if o != nil && !IsNil(o.Object) {
		return true
	}

	return false
}

// SetObject gets a reference to the given string and assigns it to the Object field.
func (o *ModelListResponse) SetObject(v string) {
	o.Object = &v
}

func (o ModelListResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ModelListResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["data"] = o.Data
	if !IsNil(o.Object) {
		toSerialize["object"] = o.Object
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *ModelListResponse) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"data",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varModelListResponse := _ModelListResponse{}

	err = json.Unmarshal(data, &varModelListResponse)

	if err != nil {
		return err
	}

	*o = ModelListResponse(varModelListResponse)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "data")
		delete(additionalProperties, "object")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableModelListResponse struct {
	value *ModelListResponse
	isSet bool
}

func (v NullableModelListResponse) Get() *ModelListResponse {
	return v.value
}

func (v *NullableModelListResponse) Set(val *ModelListResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableModelListResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableModelListResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableModelListResponse(val *ModelListResponse) *NullableModelListResponse {
	return &NullableModelListResponse{value: val, isSet: true}
}

func (v NullableModelListResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableModelListResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


