/*
mm-gateway

Provider-neutral image, video, music, speech and voice cloning gateway.

API version: 0.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package mmgateway

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the VoiceConsent type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &VoiceConsent{}

// VoiceConsent struct for VoiceConsent
type VoiceConsent struct {
	// The speaker authorized creation and use of this voice.
	Granted bool `json:"granted"`
	Language NullableString `json:"language,omitempty" validate:"regexp=^[a-z]{2\\,3}$"`
	// Absolute media URI. Inline media uses a base64 data URI.
	RecordingUri NullableString `json:"recording_uri,omitempty"`
}

type _VoiceConsent VoiceConsent

// NewVoiceConsent instantiates a new VoiceConsent object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewVoiceConsent(granted bool) *VoiceConsent {
	this := VoiceConsent{}
	this.Granted = granted
	return &this
}

// NewVoiceConsentWithDefaults instantiates a new VoiceConsent object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewVoiceConsentWithDefaults() *VoiceConsent {
	this := VoiceConsent{}
	return &this
}

// GetGranted returns the Granted field value
func (o *VoiceConsent) GetGranted() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.Granted
}

// GetGrantedOk returns a tuple with the Granted field value
// and a boolean to check if the value has been set.
func (o *VoiceConsent) GetGrantedOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Granted, true
}

// SetGranted sets field value
func (o *VoiceConsent) SetGranted(v bool) {
	o.Granted = v
}

// GetLanguage returns the Language field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *VoiceConsent) GetLanguage() string {
	if o == nil || IsNil(o.Language.Get()) {
		var ret string
		return ret
	}
	return *o.Language.Get()
}

// GetLanguageOk returns a tuple with the Language field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *VoiceConsent) GetLanguageOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Language.Get(), o.Language.IsSet()
}

// HasLanguage returns a boolean if a field has been set.
func (o *VoiceConsent) HasLanguage() bool {
	if o != nil && o.Language.IsSet() {
		return true
	}

	return false
}

// SetLanguage gets a reference to the given NullableString and assigns it to the Language field.
func (o *VoiceConsent) SetLanguage(v string) {
	o.Language.Set(&v)
}
// SetLanguageNil sets the value for Language to be an explicit nil
func (o *VoiceConsent) SetLanguageNil() {
	o.Language.Set(nil)
}

// UnsetLanguage ensures that no value is present for Language, not even an explicit nil
func (o *VoiceConsent) UnsetLanguage() {
	o.Language.Unset()
}

// GetRecordingUri returns the RecordingUri field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *VoiceConsent) GetRecordingUri() string {
	if o == nil || IsNil(o.RecordingUri.Get()) {
		var ret string
		return ret
	}
	return *o.RecordingUri.Get()
}

// GetRecordingUriOk returns a tuple with the RecordingUri field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *VoiceConsent) GetRecordingUriOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.RecordingUri.Get(), o.RecordingUri.IsSet()
}

// HasRecordingUri returns a boolean if a field has been set.
func (o *VoiceConsent) HasRecordingUri() bool {
	if o != nil && o.RecordingUri.IsSet() {
		return true
	}

	return false
}

// SetRecordingUri gets a reference to the given NullableString and assigns it to the RecordingUri field.
func (o *VoiceConsent) SetRecordingUri(v string) {
	o.RecordingUri.Set(&v)
}
// SetRecordingUriNil sets the value for RecordingUri to be an explicit nil
func (o *VoiceConsent) SetRecordingUriNil() {
	o.RecordingUri.Set(nil)
}

// UnsetRecordingUri ensures that no value is present for RecordingUri, not even an explicit nil
func (o *VoiceConsent) UnsetRecordingUri() {
	o.RecordingUri.Unset()
}

func (o VoiceConsent) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o VoiceConsent) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["granted"] = o.Granted
	if o.Language.IsSet() {
		toSerialize["language"] = o.Language.Get()
	}
	if o.RecordingUri.IsSet() {
		toSerialize["recording_uri"] = o.RecordingUri.Get()
	}
	return toSerialize, nil
}

func (o *VoiceConsent) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"granted",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varVoiceConsent := _VoiceConsent{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varVoiceConsent)

	if err != nil {
		return err
	}

	*o = VoiceConsent(varVoiceConsent)

	return err
}

type NullableVoiceConsent struct {
	value *VoiceConsent
	isSet bool
}

func (v NullableVoiceConsent) Get() *VoiceConsent {
	return v.value
}

func (v *NullableVoiceConsent) Set(val *VoiceConsent) {
	v.value = val
	v.isSet = true
}

func (v NullableVoiceConsent) IsSet() bool {
	return v.isSet
}

func (v *NullableVoiceConsent) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableVoiceConsent(val *VoiceConsent) *NullableVoiceConsent {
	return &NullableVoiceConsent{value: val, isSet: true}
}

func (v NullableVoiceConsent) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableVoiceConsent) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


