/*
mm-gateway

Provider-neutral image, video, music, speech and voice cloning gateway.

API version: 0.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package mmgateway

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the ProxyRuntime type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ProxyRuntime{}

// ProxyRuntime struct for ProxyRuntime
type ProxyRuntime struct {
	Accounts []string `json:"accounts"`
	Active bool `json:"active"`
	Domain string `json:"domain"`
	Enabled bool `json:"enabled"`
}

type _ProxyRuntime ProxyRuntime

// NewProxyRuntime instantiates a new ProxyRuntime object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewProxyRuntime(accounts []string, active bool, domain string, enabled bool) *ProxyRuntime {
	this := ProxyRuntime{}
	this.Accounts = accounts
	this.Active = active
	this.Domain = domain
	this.Enabled = enabled
	return &this
}

// NewProxyRuntimeWithDefaults instantiates a new ProxyRuntime object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewProxyRuntimeWithDefaults() *ProxyRuntime {
	this := ProxyRuntime{}
	return &this
}

// GetAccounts returns the Accounts field value
func (o *ProxyRuntime) GetAccounts() []string {
	if o == nil {
		var ret []string
		return ret
	}

	return o.Accounts
}

// GetAccountsOk returns a tuple with the Accounts field value
// and a boolean to check if the value has been set.
func (o *ProxyRuntime) GetAccountsOk() ([]string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Accounts, true
}

// SetAccounts sets field value
func (o *ProxyRuntime) SetAccounts(v []string) {
	o.Accounts = v
}

// GetActive returns the Active field value
func (o *ProxyRuntime) GetActive() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.Active
}

// GetActiveOk returns a tuple with the Active field value
// and a boolean to check if the value has been set.
func (o *ProxyRuntime) GetActiveOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Active, true
}

// SetActive sets field value
func (o *ProxyRuntime) SetActive(v bool) {
	o.Active = v
}

// GetDomain returns the Domain field value
func (o *ProxyRuntime) GetDomain() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Domain
}

// GetDomainOk returns a tuple with the Domain field value
// and a boolean to check if the value has been set.
func (o *ProxyRuntime) GetDomainOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Domain, true
}

// SetDomain sets field value
func (o *ProxyRuntime) SetDomain(v string) {
	o.Domain = v
}

// GetEnabled returns the Enabled field value
func (o *ProxyRuntime) GetEnabled() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.Enabled
}

// GetEnabledOk returns a tuple with the Enabled field value
// and a boolean to check if the value has been set.
func (o *ProxyRuntime) GetEnabledOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Enabled, true
}

// SetEnabled sets field value
func (o *ProxyRuntime) SetEnabled(v bool) {
	o.Enabled = v
}

func (o ProxyRuntime) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ProxyRuntime) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["accounts"] = o.Accounts
	toSerialize["active"] = o.Active
	toSerialize["domain"] = o.Domain
	toSerialize["enabled"] = o.Enabled
	return toSerialize, nil
}

func (o *ProxyRuntime) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"accounts",
		"active",
		"domain",
		"enabled",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varProxyRuntime := _ProxyRuntime{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varProxyRuntime)

	if err != nil {
		return err
	}

	*o = ProxyRuntime(varProxyRuntime)

	return err
}

type NullableProxyRuntime struct {
	value *ProxyRuntime
	isSet bool
}

func (v NullableProxyRuntime) Get() *ProxyRuntime {
	return v.value
}

func (v *NullableProxyRuntime) Set(val *ProxyRuntime) {
	v.value = val
	v.isSet = true
}

func (v NullableProxyRuntime) IsSet() bool {
	return v.isSet
}

func (v *NullableProxyRuntime) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableProxyRuntime(val *ProxyRuntime) *NullableProxyRuntime {
	return &NullableProxyRuntime{value: val, isSet: true}
}

func (v NullableProxyRuntime) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableProxyRuntime) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


