/*
mm-gateway

Provider-neutral image, video, music, speech and voice cloning gateway.

API version: 0.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package mmgateway

import (
	"encoding/json"
	"fmt"
)

// checks if the AudioRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &AudioRequest{}

// AudioRequest struct for AudioRequest
type AudioRequest struct {
	Input []TextInput `json:"input"`
	// Client-owned metadata returned unchanged with the task.
	Metadata map[string]interface{} `json:"metadata,omitempty"`
	// Model id returned by GET /v1/models, or omit / set to `auto` to let the gateway auto-route to a backend whose limits fit the request's input (modalities, dimensions, duration, ...).
	Model NullableString `json:"model,omitempty"`
	Parameters *AudioParameters `json:"parameters,omitempty"`
	Routing NullableRoutingDirective `json:"routing,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _AudioRequest AudioRequest

// NewAudioRequest instantiates a new AudioRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAudioRequest(input []TextInput) *AudioRequest {
	this := AudioRequest{}
	this.Input = input
	return &this
}

// NewAudioRequestWithDefaults instantiates a new AudioRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAudioRequestWithDefaults() *AudioRequest {
	this := AudioRequest{}
	return &this
}

// GetInput returns the Input field value
func (o *AudioRequest) GetInput() []TextInput {
	if o == nil {
		var ret []TextInput
		return ret
	}

	return o.Input
}

// GetInputOk returns a tuple with the Input field value
// and a boolean to check if the value has been set.
func (o *AudioRequest) GetInputOk() ([]TextInput, bool) {
	if o == nil {
		return nil, false
	}
	return o.Input, true
}

// SetInput sets field value
func (o *AudioRequest) SetInput(v []TextInput) {
	o.Input = v
}

// GetMetadata returns the Metadata field value if set, zero value otherwise.
func (o *AudioRequest) GetMetadata() map[string]interface{} {
	if o == nil || IsNil(o.Metadata) {
		var ret map[string]interface{}
		return ret
	}
	return o.Metadata
}

// GetMetadataOk returns a tuple with the Metadata field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AudioRequest) GetMetadataOk() (map[string]interface{}, bool) {
	if o == nil || IsNil(o.Metadata) {
		return map[string]interface{}{}, false
	}
	return o.Metadata, true
}

// HasMetadata returns a boolean if a field has been set.
func (o *AudioRequest) HasMetadata() bool {
	if o != nil && !IsNil(o.Metadata) {
		return true
	}

	return false
}

// SetMetadata gets a reference to the given map[string]interface{} and assigns it to the Metadata field.
func (o *AudioRequest) SetMetadata(v map[string]interface{}) {
	o.Metadata = v
}

// GetModel returns the Model field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *AudioRequest) GetModel() string {
	if o == nil || IsNil(o.Model.Get()) {
		var ret string
		return ret
	}
	return *o.Model.Get()
}

// GetModelOk returns a tuple with the Model field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *AudioRequest) GetModelOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Model.Get(), o.Model.IsSet()
}

// HasModel returns a boolean if a field has been set.
func (o *AudioRequest) HasModel() bool {
	if o != nil && o.Model.IsSet() {
		return true
	}

	return false
}

// SetModel gets a reference to the given NullableString and assigns it to the Model field.
func (o *AudioRequest) SetModel(v string) {
	o.Model.Set(&v)
}
// SetModelNil sets the value for Model to be an explicit nil
func (o *AudioRequest) SetModelNil() {
	o.Model.Set(nil)
}

// UnsetModel ensures that no value is present for Model, not even an explicit nil
func (o *AudioRequest) UnsetModel() {
	o.Model.Unset()
}

// GetParameters returns the Parameters field value if set, zero value otherwise.
func (o *AudioRequest) GetParameters() AudioParameters {
	if o == nil || IsNil(o.Parameters) {
		var ret AudioParameters
		return ret
	}
	return *o.Parameters
}

// GetParametersOk returns a tuple with the Parameters field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AudioRequest) GetParametersOk() (*AudioParameters, bool) {
	if o == nil || IsNil(o.Parameters) {
		return nil, false
	}
	return o.Parameters, true
}

// HasParameters returns a boolean if a field has been set.
func (o *AudioRequest) HasParameters() bool {
	if o != nil && !IsNil(o.Parameters) {
		return true
	}

	return false
}

// SetParameters gets a reference to the given AudioParameters and assigns it to the Parameters field.
func (o *AudioRequest) SetParameters(v AudioParameters) {
	o.Parameters = &v
}

// GetRouting returns the Routing field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *AudioRequest) GetRouting() RoutingDirective {
	if o == nil || IsNil(o.Routing.Get()) {
		var ret RoutingDirective
		return ret
	}
	return *o.Routing.Get()
}

// GetRoutingOk returns a tuple with the Routing field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *AudioRequest) GetRoutingOk() (*RoutingDirective, bool) {
	if o == nil {
		return nil, false
	}
	return o.Routing.Get(), o.Routing.IsSet()
}

// HasRouting returns a boolean if a field has been set.
func (o *AudioRequest) HasRouting() bool {
	if o != nil && o.Routing.IsSet() {
		return true
	}

	return false
}

// SetRouting gets a reference to the given NullableRoutingDirective and assigns it to the Routing field.
func (o *AudioRequest) SetRouting(v RoutingDirective) {
	o.Routing.Set(&v)
}
// SetRoutingNil sets the value for Routing to be an explicit nil
func (o *AudioRequest) SetRoutingNil() {
	o.Routing.Set(nil)
}

// UnsetRouting ensures that no value is present for Routing, not even an explicit nil
func (o *AudioRequest) UnsetRouting() {
	o.Routing.Unset()
}

func (o AudioRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o AudioRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["input"] = o.Input
	if !IsNil(o.Metadata) {
		toSerialize["metadata"] = o.Metadata
	}
	if o.Model.IsSet() {
		toSerialize["model"] = o.Model.Get()
	}
	if !IsNil(o.Parameters) {
		toSerialize["parameters"] = o.Parameters
	}
	if o.Routing.IsSet() {
		toSerialize["routing"] = o.Routing.Get()
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *AudioRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"input",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varAudioRequest := _AudioRequest{}

	err = json.Unmarshal(data, &varAudioRequest)

	if err != nil {
		return err
	}

	*o = AudioRequest(varAudioRequest)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "input")
		delete(additionalProperties, "metadata")
		delete(additionalProperties, "model")
		delete(additionalProperties, "parameters")
		delete(additionalProperties, "routing")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableAudioRequest struct {
	value *AudioRequest
	isSet bool
}

func (v NullableAudioRequest) Get() *AudioRequest {
	return v.value
}

func (v *NullableAudioRequest) Set(val *AudioRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableAudioRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableAudioRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAudioRequest(val *AudioRequest) *NullableAudioRequest {
	return &NullableAudioRequest{value: val, isSet: true}
}

func (v NullableAudioRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAudioRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


