/*
mm-gateway

Provider-neutral image, video, music, speech and voice cloning gateway.

API version: 0.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package mmgateway

import (
	"encoding/json"
	"fmt"
)

// checks if the VoiceCloneRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &VoiceCloneRequest{}

// VoiceCloneRequest struct for VoiceCloneRequest
type VoiceCloneRequest struct {
	Consent VoiceConsent `json:"consent"`
	Input []VoiceSampleInput `json:"input"`
	// Client-owned metadata returned unchanged with the task.
	Metadata map[string]interface{} `json:"metadata,omitempty"`
	// Model id returned by GET /v1/models, or omit / set to `auto` to let the gateway auto-route to a backend whose limits fit the request's input (modalities, dimensions, duration, ...).
	Model NullableString `json:"model,omitempty"`
	Parameters VoiceParameters `json:"parameters"`
	Routing NullableRoutingDirective `json:"routing,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _VoiceCloneRequest VoiceCloneRequest

// NewVoiceCloneRequest instantiates a new VoiceCloneRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewVoiceCloneRequest(consent VoiceConsent, input []VoiceSampleInput, parameters VoiceParameters) *VoiceCloneRequest {
	this := VoiceCloneRequest{}
	this.Consent = consent
	this.Input = input
	this.Parameters = parameters
	return &this
}

// NewVoiceCloneRequestWithDefaults instantiates a new VoiceCloneRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewVoiceCloneRequestWithDefaults() *VoiceCloneRequest {
	this := VoiceCloneRequest{}
	return &this
}

// GetConsent returns the Consent field value
func (o *VoiceCloneRequest) GetConsent() VoiceConsent {
	if o == nil {
		var ret VoiceConsent
		return ret
	}

	return o.Consent
}

// GetConsentOk returns a tuple with the Consent field value
// and a boolean to check if the value has been set.
func (o *VoiceCloneRequest) GetConsentOk() (*VoiceConsent, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Consent, true
}

// SetConsent sets field value
func (o *VoiceCloneRequest) SetConsent(v VoiceConsent) {
	o.Consent = v
}

// GetInput returns the Input field value
func (o *VoiceCloneRequest) GetInput() []VoiceSampleInput {
	if o == nil {
		var ret []VoiceSampleInput
		return ret
	}

	return o.Input
}

// GetInputOk returns a tuple with the Input field value
// and a boolean to check if the value has been set.
func (o *VoiceCloneRequest) GetInputOk() ([]VoiceSampleInput, bool) {
	if o == nil {
		return nil, false
	}
	return o.Input, true
}

// SetInput sets field value
func (o *VoiceCloneRequest) SetInput(v []VoiceSampleInput) {
	o.Input = v
}

// GetMetadata returns the Metadata field value if set, zero value otherwise.
func (o *VoiceCloneRequest) GetMetadata() map[string]interface{} {
	if o == nil || IsNil(o.Metadata) {
		var ret map[string]interface{}
		return ret
	}
	return o.Metadata
}

// GetMetadataOk returns a tuple with the Metadata field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *VoiceCloneRequest) GetMetadataOk() (map[string]interface{}, bool) {
	if o == nil || IsNil(o.Metadata) {
		return map[string]interface{}{}, false
	}
	return o.Metadata, true
}

// HasMetadata returns a boolean if a field has been set.
func (o *VoiceCloneRequest) HasMetadata() bool {
	if o != nil && !IsNil(o.Metadata) {
		return true
	}

	return false
}

// SetMetadata gets a reference to the given map[string]interface{} and assigns it to the Metadata field.
func (o *VoiceCloneRequest) SetMetadata(v map[string]interface{}) {
	o.Metadata = v
}

// GetModel returns the Model field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *VoiceCloneRequest) GetModel() string {
	if o == nil || IsNil(o.Model.Get()) {
		var ret string
		return ret
	}
	return *o.Model.Get()
}

// GetModelOk returns a tuple with the Model field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *VoiceCloneRequest) GetModelOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Model.Get(), o.Model.IsSet()
}

// HasModel returns a boolean if a field has been set.
func (o *VoiceCloneRequest) HasModel() bool {
	if o != nil && o.Model.IsSet() {
		return true
	}

	return false
}

// SetModel gets a reference to the given NullableString and assigns it to the Model field.
func (o *VoiceCloneRequest) SetModel(v string) {
	o.Model.Set(&v)
}
// SetModelNil sets the value for Model to be an explicit nil
func (o *VoiceCloneRequest) SetModelNil() {
	o.Model.Set(nil)
}

// UnsetModel ensures that no value is present for Model, not even an explicit nil
func (o *VoiceCloneRequest) UnsetModel() {
	o.Model.Unset()
}

// GetParameters returns the Parameters field value
func (o *VoiceCloneRequest) GetParameters() VoiceParameters {
	if o == nil {
		var ret VoiceParameters
		return ret
	}

	return o.Parameters
}

// GetParametersOk returns a tuple with the Parameters field value
// and a boolean to check if the value has been set.
func (o *VoiceCloneRequest) GetParametersOk() (*VoiceParameters, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Parameters, true
}

// SetParameters sets field value
func (o *VoiceCloneRequest) SetParameters(v VoiceParameters) {
	o.Parameters = v
}

// GetRouting returns the Routing field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *VoiceCloneRequest) GetRouting() RoutingDirective {
	if o == nil || IsNil(o.Routing.Get()) {
		var ret RoutingDirective
		return ret
	}
	return *o.Routing.Get()
}

// GetRoutingOk returns a tuple with the Routing field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *VoiceCloneRequest) GetRoutingOk() (*RoutingDirective, bool) {
	if o == nil {
		return nil, false
	}
	return o.Routing.Get(), o.Routing.IsSet()
}

// HasRouting returns a boolean if a field has been set.
func (o *VoiceCloneRequest) HasRouting() bool {
	if o != nil && o.Routing.IsSet() {
		return true
	}

	return false
}

// SetRouting gets a reference to the given NullableRoutingDirective and assigns it to the Routing field.
func (o *VoiceCloneRequest) SetRouting(v RoutingDirective) {
	o.Routing.Set(&v)
}
// SetRoutingNil sets the value for Routing to be an explicit nil
func (o *VoiceCloneRequest) SetRoutingNil() {
	o.Routing.Set(nil)
}

// UnsetRouting ensures that no value is present for Routing, not even an explicit nil
func (o *VoiceCloneRequest) UnsetRouting() {
	o.Routing.Unset()
}

func (o VoiceCloneRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o VoiceCloneRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["consent"] = o.Consent
	toSerialize["input"] = o.Input
	if !IsNil(o.Metadata) {
		toSerialize["metadata"] = o.Metadata
	}
	if o.Model.IsSet() {
		toSerialize["model"] = o.Model.Get()
	}
	toSerialize["parameters"] = o.Parameters
	if o.Routing.IsSet() {
		toSerialize["routing"] = o.Routing.Get()
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *VoiceCloneRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"consent",
		"input",
		"parameters",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varVoiceCloneRequest := _VoiceCloneRequest{}

	err = json.Unmarshal(data, &varVoiceCloneRequest)

	if err != nil {
		return err
	}

	*o = VoiceCloneRequest(varVoiceCloneRequest)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "consent")
		delete(additionalProperties, "input")
		delete(additionalProperties, "metadata")
		delete(additionalProperties, "model")
		delete(additionalProperties, "parameters")
		delete(additionalProperties, "routing")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableVoiceCloneRequest struct {
	value *VoiceCloneRequest
	isSet bool
}

func (v NullableVoiceCloneRequest) Get() *VoiceCloneRequest {
	return v.value
}

func (v *NullableVoiceCloneRequest) Set(val *VoiceCloneRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableVoiceCloneRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableVoiceCloneRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableVoiceCloneRequest(val *VoiceCloneRequest) *NullableVoiceCloneRequest {
	return &NullableVoiceCloneRequest{value: val, isSet: true}
}

func (v NullableVoiceCloneRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableVoiceCloneRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


