/*
mm-gateway

Provider-neutral image, video, music, speech and voice cloning gateway.

API version: 0.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package mmgateway

import (
	"encoding/json"
	"fmt"
	"gopkg.in/validator.v2"
)

// InputInner1 - struct for InputInner1
type InputInner1 struct {
	LyricsInput *LyricsInput
	MusicAudioInput *MusicAudioInput
	MusicImageInput *MusicImageInput
	TextInput *TextInput
}

// LyricsInputAsInputInner1 is a convenience function that returns LyricsInput wrapped in InputInner1
func LyricsInputAsInputInner1(v *LyricsInput) InputInner1 {
	return InputInner1{
		LyricsInput: v,
	}
}

// MusicAudioInputAsInputInner1 is a convenience function that returns MusicAudioInput wrapped in InputInner1
func MusicAudioInputAsInputInner1(v *MusicAudioInput) InputInner1 {
	return InputInner1{
		MusicAudioInput: v,
	}
}

// MusicImageInputAsInputInner1 is a convenience function that returns MusicImageInput wrapped in InputInner1
func MusicImageInputAsInputInner1(v *MusicImageInput) InputInner1 {
	return InputInner1{
		MusicImageInput: v,
	}
}

// TextInputAsInputInner1 is a convenience function that returns TextInput wrapped in InputInner1
func TextInputAsInputInner1(v *TextInput) InputInner1 {
	return InputInner1{
		TextInput: v,
	}
}


// Unmarshal JSON data into one of the pointers in the struct
func (dst *InputInner1) UnmarshalJSON(data []byte) error {
	var err error
	match := 0
	// try to unmarshal data into LyricsInput
	err = newStrictDecoder(data).Decode(&dst.LyricsInput)
	if err == nil {
		jsonLyricsInput, _ := json.Marshal(dst.LyricsInput)
		if string(jsonLyricsInput) == "{}" { // empty struct
			dst.LyricsInput = nil
		} else {
			if err = validator.Validate(dst.LyricsInput); err != nil {
				dst.LyricsInput = nil
			} else {
				match++
			}
		}
	} else {
		dst.LyricsInput = nil
	}

	// try to unmarshal data into MusicAudioInput
	err = newStrictDecoder(data).Decode(&dst.MusicAudioInput)
	if err == nil {
		jsonMusicAudioInput, _ := json.Marshal(dst.MusicAudioInput)
		if string(jsonMusicAudioInput) == "{}" { // empty struct
			dst.MusicAudioInput = nil
		} else {
			if err = validator.Validate(dst.MusicAudioInput); err != nil {
				dst.MusicAudioInput = nil
			} else {
				match++
			}
		}
	} else {
		dst.MusicAudioInput = nil
	}

	// try to unmarshal data into MusicImageInput
	err = newStrictDecoder(data).Decode(&dst.MusicImageInput)
	if err == nil {
		jsonMusicImageInput, _ := json.Marshal(dst.MusicImageInput)
		if string(jsonMusicImageInput) == "{}" { // empty struct
			dst.MusicImageInput = nil
		} else {
			if err = validator.Validate(dst.MusicImageInput); err != nil {
				dst.MusicImageInput = nil
			} else {
				match++
			}
		}
	} else {
		dst.MusicImageInput = nil
	}

	// try to unmarshal data into TextInput
	err = newStrictDecoder(data).Decode(&dst.TextInput)
	if err == nil {
		jsonTextInput, _ := json.Marshal(dst.TextInput)
		if string(jsonTextInput) == "{}" { // empty struct
			dst.TextInput = nil
		} else {
			if err = validator.Validate(dst.TextInput); err != nil {
				dst.TextInput = nil
			} else {
				match++
			}
		}
	} else {
		dst.TextInput = nil
	}

	if match > 1 { // more than 1 match
		// reset to nil
		dst.LyricsInput = nil
		dst.MusicAudioInput = nil
		dst.MusicImageInput = nil
		dst.TextInput = nil

		return fmt.Errorf("data matches more than one schema in oneOf(InputInner1)")
	} else if match == 1 {
		return nil // exactly one match
	} else { // no match
        if err != nil {
            return fmt.Errorf("data failed to match schemas in oneOf(InputInner1): %v", err)
        } else {
            return fmt.Errorf("data failed to match schemas in oneOf(InputInner1)")
        }
        if err != nil {
            return fmt.Errorf("data failed to match schemas in oneOf(InputInner1): %v", err)
        } else {
            return fmt.Errorf("data failed to match schemas in oneOf(InputInner1)")
        }
        if err != nil {
            return fmt.Errorf("data failed to match schemas in oneOf(InputInner1): %v", err)
        } else {
            return fmt.Errorf("data failed to match schemas in oneOf(InputInner1)")
        }
        if err != nil {
            return fmt.Errorf("data failed to match schemas in oneOf(InputInner1): %v", err)
        } else {
            return fmt.Errorf("data failed to match schemas in oneOf(InputInner1)")
        }
	}
}

// Marshal data from the first non-nil pointers in the struct to JSON
func (src InputInner1) MarshalJSON() ([]byte, error) {
	if src.LyricsInput != nil {
		return json.Marshal(&src.LyricsInput)
	}

	if src.MusicAudioInput != nil {
		return json.Marshal(&src.MusicAudioInput)
	}

	if src.MusicImageInput != nil {
		return json.Marshal(&src.MusicImageInput)
	}

	if src.TextInput != nil {
		return json.Marshal(&src.TextInput)
	}

	return nil, nil // no data in oneOf schemas
}

// Get the actual instance
func (obj *InputInner1) GetActualInstance() (interface{}) {
	if obj == nil {
		return nil
	}
	if obj.LyricsInput != nil {
		return obj.LyricsInput
	}

	if obj.MusicAudioInput != nil {
		return obj.MusicAudioInput
	}

	if obj.MusicImageInput != nil {
		return obj.MusicImageInput
	}

	if obj.TextInput != nil {
		return obj.TextInput
	}

	// all schemas are nil
	return nil
}

// Get the actual instance value
func (obj InputInner1) GetActualInstanceValue() (interface{}) {
	if obj.LyricsInput != nil {
		return *obj.LyricsInput
	}

	if obj.MusicAudioInput != nil {
		return *obj.MusicAudioInput
	}

	if obj.MusicImageInput != nil {
		return *obj.MusicImageInput
	}

	if obj.TextInput != nil {
		return *obj.TextInput
	}

	// all schemas are nil
	return nil
}

type NullableInputInner1 struct {
	value *InputInner1
	isSet bool
}

func (v NullableInputInner1) Get() *InputInner1 {
	return v.value
}

func (v *NullableInputInner1) Set(val *InputInner1) {
	v.value = val
	v.isSet = true
}

func (v NullableInputInner1) IsSet() bool {
	return v.isSet
}

func (v *NullableInputInner1) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableInputInner1(val *InputInner1) *NullableInputInner1 {
	return &NullableInputInner1{value: val, isSet: true}
}

func (v NullableInputInner1) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableInputInner1) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


