/*
mm-gateway

Provider-neutral image, video, music, speech and voice cloning gateway.

API version: 0.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package mmgateway

import (
	"encoding/json"
	"fmt"
)

// checks if the VideoRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &VideoRequest{}

// VideoRequest struct for VideoRequest
type VideoRequest struct {
	// Non-empty ordered video-generation inputs.
	Input []InputInner2 `json:"input"`
	// Client-owned metadata returned unchanged with the task.
	Metadata map[string]interface{} `json:"metadata,omitempty"`
	// Model id returned by GET /v1/models, or omit / set to `auto` to let the gateway auto-route to a backend whose limits fit the request's input (modalities, dimensions, duration, ...).
	Model NullableString `json:"model,omitempty"`
	Parameters *VideoParameters `json:"parameters,omitempty"`
	Routing NullableRoutingDirective `json:"routing,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _VideoRequest VideoRequest

// NewVideoRequest instantiates a new VideoRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewVideoRequest(input []InputInner2) *VideoRequest {
	this := VideoRequest{}
	this.Input = input
	return &this
}

// NewVideoRequestWithDefaults instantiates a new VideoRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewVideoRequestWithDefaults() *VideoRequest {
	this := VideoRequest{}
	return &this
}

// GetInput returns the Input field value
func (o *VideoRequest) GetInput() []InputInner2 {
	if o == nil {
		var ret []InputInner2
		return ret
	}

	return o.Input
}

// GetInputOk returns a tuple with the Input field value
// and a boolean to check if the value has been set.
func (o *VideoRequest) GetInputOk() ([]InputInner2, bool) {
	if o == nil {
		return nil, false
	}
	return o.Input, true
}

// SetInput sets field value
func (o *VideoRequest) SetInput(v []InputInner2) {
	o.Input = v
}

// GetMetadata returns the Metadata field value if set, zero value otherwise.
func (o *VideoRequest) GetMetadata() map[string]interface{} {
	if o == nil || IsNil(o.Metadata) {
		var ret map[string]interface{}
		return ret
	}
	return o.Metadata
}

// GetMetadataOk returns a tuple with the Metadata field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *VideoRequest) GetMetadataOk() (map[string]interface{}, bool) {
	if o == nil || IsNil(o.Metadata) {
		return map[string]interface{}{}, false
	}
	return o.Metadata, true
}

// HasMetadata returns a boolean if a field has been set.
func (o *VideoRequest) HasMetadata() bool {
	if o != nil && !IsNil(o.Metadata) {
		return true
	}

	return false
}

// SetMetadata gets a reference to the given map[string]interface{} and assigns it to the Metadata field.
func (o *VideoRequest) SetMetadata(v map[string]interface{}) {
	o.Metadata = v
}

// GetModel returns the Model field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *VideoRequest) GetModel() string {
	if o == nil || IsNil(o.Model.Get()) {
		var ret string
		return ret
	}
	return *o.Model.Get()
}

// GetModelOk returns a tuple with the Model field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *VideoRequest) GetModelOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Model.Get(), o.Model.IsSet()
}

// HasModel returns a boolean if a field has been set.
func (o *VideoRequest) HasModel() bool {
	if o != nil && o.Model.IsSet() {
		return true
	}

	return false
}

// SetModel gets a reference to the given NullableString and assigns it to the Model field.
func (o *VideoRequest) SetModel(v string) {
	o.Model.Set(&v)
}
// SetModelNil sets the value for Model to be an explicit nil
func (o *VideoRequest) SetModelNil() {
	o.Model.Set(nil)
}

// UnsetModel ensures that no value is present for Model, not even an explicit nil
func (o *VideoRequest) UnsetModel() {
	o.Model.Unset()
}

// GetParameters returns the Parameters field value if set, zero value otherwise.
func (o *VideoRequest) GetParameters() VideoParameters {
	if o == nil || IsNil(o.Parameters) {
		var ret VideoParameters
		return ret
	}
	return *o.Parameters
}

// GetParametersOk returns a tuple with the Parameters field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *VideoRequest) GetParametersOk() (*VideoParameters, bool) {
	if o == nil || IsNil(o.Parameters) {
		return nil, false
	}
	return o.Parameters, true
}

// HasParameters returns a boolean if a field has been set.
func (o *VideoRequest) HasParameters() bool {
	if o != nil && !IsNil(o.Parameters) {
		return true
	}

	return false
}

// SetParameters gets a reference to the given VideoParameters and assigns it to the Parameters field.
func (o *VideoRequest) SetParameters(v VideoParameters) {
	o.Parameters = &v
}

// GetRouting returns the Routing field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *VideoRequest) GetRouting() RoutingDirective {
	if o == nil || IsNil(o.Routing.Get()) {
		var ret RoutingDirective
		return ret
	}
	return *o.Routing.Get()
}

// GetRoutingOk returns a tuple with the Routing field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *VideoRequest) GetRoutingOk() (*RoutingDirective, bool) {
	if o == nil {
		return nil, false
	}
	return o.Routing.Get(), o.Routing.IsSet()
}

// HasRouting returns a boolean if a field has been set.
func (o *VideoRequest) HasRouting() bool {
	if o != nil && o.Routing.IsSet() {
		return true
	}

	return false
}

// SetRouting gets a reference to the given NullableRoutingDirective and assigns it to the Routing field.
func (o *VideoRequest) SetRouting(v RoutingDirective) {
	o.Routing.Set(&v)
}
// SetRoutingNil sets the value for Routing to be an explicit nil
func (o *VideoRequest) SetRoutingNil() {
	o.Routing.Set(nil)
}

// UnsetRouting ensures that no value is present for Routing, not even an explicit nil
func (o *VideoRequest) UnsetRouting() {
	o.Routing.Unset()
}

func (o VideoRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o VideoRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["input"] = o.Input
	if !IsNil(o.Metadata) {
		toSerialize["metadata"] = o.Metadata
	}
	if o.Model.IsSet() {
		toSerialize["model"] = o.Model.Get()
	}
	if !IsNil(o.Parameters) {
		toSerialize["parameters"] = o.Parameters
	}
	if o.Routing.IsSet() {
		toSerialize["routing"] = o.Routing.Get()
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *VideoRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"input",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varVideoRequest := _VideoRequest{}

	err = json.Unmarshal(data, &varVideoRequest)

	if err != nil {
		return err
	}

	*o = VideoRequest(varVideoRequest)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "input")
		delete(additionalProperties, "metadata")
		delete(additionalProperties, "model")
		delete(additionalProperties, "parameters")
		delete(additionalProperties, "routing")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableVideoRequest struct {
	value *VideoRequest
	isSet bool
}

func (v NullableVideoRequest) Get() *VideoRequest {
	return v.value
}

func (v *NullableVideoRequest) Set(val *VideoRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableVideoRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableVideoRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableVideoRequest(val *VideoRequest) *NullableVideoRequest {
	return &NullableVideoRequest{value: val, isSet: true}
}

func (v NullableVideoRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableVideoRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


