/*
mm-gateway

Provider-neutral image, video, music, speech and voice cloning gateway.

API version: 0.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package mmgateway

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the ManagedTask type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ManagedTask{}

// ManagedTask struct for ManagedTask
type ManagedTask struct {
	Backend string `json:"backend"`
	CompletedAt NullableInt32 `json:"completed_at,omitempty"`
	CreatedAt int32 `json:"created_at"`
	Id string `json:"id"`
	Modality string `json:"modality"`
	Model string `json:"model"`
	OwnerKeyId string `json:"owner_key_id"`
	Status string `json:"status"`
}

type _ManagedTask ManagedTask

// NewManagedTask instantiates a new ManagedTask object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewManagedTask(backend string, createdAt int32, id string, modality string, model string, ownerKeyId string, status string) *ManagedTask {
	this := ManagedTask{}
	this.Backend = backend
	this.CreatedAt = createdAt
	this.Id = id
	this.Modality = modality
	this.Model = model
	this.OwnerKeyId = ownerKeyId
	this.Status = status
	return &this
}

// NewManagedTaskWithDefaults instantiates a new ManagedTask object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewManagedTaskWithDefaults() *ManagedTask {
	this := ManagedTask{}
	return &this
}

// GetBackend returns the Backend field value
func (o *ManagedTask) GetBackend() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Backend
}

// GetBackendOk returns a tuple with the Backend field value
// and a boolean to check if the value has been set.
func (o *ManagedTask) GetBackendOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Backend, true
}

// SetBackend sets field value
func (o *ManagedTask) SetBackend(v string) {
	o.Backend = v
}

// GetCompletedAt returns the CompletedAt field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *ManagedTask) GetCompletedAt() int32 {
	if o == nil || IsNil(o.CompletedAt.Get()) {
		var ret int32
		return ret
	}
	return *o.CompletedAt.Get()
}

// GetCompletedAtOk returns a tuple with the CompletedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ManagedTask) GetCompletedAtOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return o.CompletedAt.Get(), o.CompletedAt.IsSet()
}

// HasCompletedAt returns a boolean if a field has been set.
func (o *ManagedTask) HasCompletedAt() bool {
	if o != nil && o.CompletedAt.IsSet() {
		return true
	}

	return false
}

// SetCompletedAt gets a reference to the given NullableInt32 and assigns it to the CompletedAt field.
func (o *ManagedTask) SetCompletedAt(v int32) {
	o.CompletedAt.Set(&v)
}
// SetCompletedAtNil sets the value for CompletedAt to be an explicit nil
func (o *ManagedTask) SetCompletedAtNil() {
	o.CompletedAt.Set(nil)
}

// UnsetCompletedAt ensures that no value is present for CompletedAt, not even an explicit nil
func (o *ManagedTask) UnsetCompletedAt() {
	o.CompletedAt.Unset()
}

// GetCreatedAt returns the CreatedAt field value
func (o *ManagedTask) GetCreatedAt() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.CreatedAt
}

// GetCreatedAtOk returns a tuple with the CreatedAt field value
// and a boolean to check if the value has been set.
func (o *ManagedTask) GetCreatedAtOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.CreatedAt, true
}

// SetCreatedAt sets field value
func (o *ManagedTask) SetCreatedAt(v int32) {
	o.CreatedAt = v
}

// GetId returns the Id field value
func (o *ManagedTask) GetId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *ManagedTask) GetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *ManagedTask) SetId(v string) {
	o.Id = v
}

// GetModality returns the Modality field value
func (o *ManagedTask) GetModality() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Modality
}

// GetModalityOk returns a tuple with the Modality field value
// and a boolean to check if the value has been set.
func (o *ManagedTask) GetModalityOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Modality, true
}

// SetModality sets field value
func (o *ManagedTask) SetModality(v string) {
	o.Modality = v
}

// GetModel returns the Model field value
func (o *ManagedTask) GetModel() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Model
}

// GetModelOk returns a tuple with the Model field value
// and a boolean to check if the value has been set.
func (o *ManagedTask) GetModelOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Model, true
}

// SetModel sets field value
func (o *ManagedTask) SetModel(v string) {
	o.Model = v
}

// GetOwnerKeyId returns the OwnerKeyId field value
func (o *ManagedTask) GetOwnerKeyId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.OwnerKeyId
}

// GetOwnerKeyIdOk returns a tuple with the OwnerKeyId field value
// and a boolean to check if the value has been set.
func (o *ManagedTask) GetOwnerKeyIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.OwnerKeyId, true
}

// SetOwnerKeyId sets field value
func (o *ManagedTask) SetOwnerKeyId(v string) {
	o.OwnerKeyId = v
}

// GetStatus returns the Status field value
func (o *ManagedTask) GetStatus() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Status
}

// GetStatusOk returns a tuple with the Status field value
// and a boolean to check if the value has been set.
func (o *ManagedTask) GetStatusOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Status, true
}

// SetStatus sets field value
func (o *ManagedTask) SetStatus(v string) {
	o.Status = v
}

func (o ManagedTask) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ManagedTask) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["backend"] = o.Backend
	if o.CompletedAt.IsSet() {
		toSerialize["completed_at"] = o.CompletedAt.Get()
	}
	toSerialize["created_at"] = o.CreatedAt
	toSerialize["id"] = o.Id
	toSerialize["modality"] = o.Modality
	toSerialize["model"] = o.Model
	toSerialize["owner_key_id"] = o.OwnerKeyId
	toSerialize["status"] = o.Status
	return toSerialize, nil
}

func (o *ManagedTask) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"backend",
		"created_at",
		"id",
		"modality",
		"model",
		"owner_key_id",
		"status",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varManagedTask := _ManagedTask{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varManagedTask)

	if err != nil {
		return err
	}

	*o = ManagedTask(varManagedTask)

	return err
}

type NullableManagedTask struct {
	value *ManagedTask
	isSet bool
}

func (v NullableManagedTask) Get() *ManagedTask {
	return v.value
}

func (v *NullableManagedTask) Set(val *ManagedTask) {
	v.value = val
	v.isSet = true
}

func (v NullableManagedTask) IsSet() bool {
	return v.isSet
}

func (v *NullableManagedTask) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableManagedTask(val *ManagedTask) *NullableManagedTask {
	return &NullableManagedTask{value: val, isSet: true}
}

func (v NullableManagedTask) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableManagedTask) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


