/*
mm-gateway

Provider-neutral image, video, music, speech and voice cloning gateway.

API version: 0.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package mmgateway

import (
	"encoding/json"
	"fmt"
)

// checks if the EstimateResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &EstimateResponse{}

// EstimateResponse The routing and cost a create would get, without creating a task.
type EstimateResponse struct {
	Budget NullableBudgetState `json:"budget,omitempty"`
	Candidates []EstimateCandidate `json:"candidates,omitempty"`
	Currency *string `json:"currency,omitempty"`
	EstimatedCost NullableFloat32 `json:"estimated_cost,omitempty"`
	Modality string `json:"modality"`
	Model NullableString `json:"model,omitempty"`
	Object *string `json:"object,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _EstimateResponse EstimateResponse

// NewEstimateResponse instantiates a new EstimateResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewEstimateResponse(modality string) *EstimateResponse {
	this := EstimateResponse{}
	var currency string = "USD"
	this.Currency = &currency
	this.Modality = modality
	var object string = "estimate"
	this.Object = &object
	return &this
}

// NewEstimateResponseWithDefaults instantiates a new EstimateResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewEstimateResponseWithDefaults() *EstimateResponse {
	this := EstimateResponse{}
	var currency string = "USD"
	this.Currency = &currency
	var object string = "estimate"
	this.Object = &object
	return &this
}

// GetBudget returns the Budget field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *EstimateResponse) GetBudget() BudgetState {
	if o == nil || IsNil(o.Budget.Get()) {
		var ret BudgetState
		return ret
	}
	return *o.Budget.Get()
}

// GetBudgetOk returns a tuple with the Budget field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *EstimateResponse) GetBudgetOk() (*BudgetState, bool) {
	if o == nil {
		return nil, false
	}
	return o.Budget.Get(), o.Budget.IsSet()
}

// HasBudget returns a boolean if a field has been set.
func (o *EstimateResponse) HasBudget() bool {
	if o != nil && o.Budget.IsSet() {
		return true
	}

	return false
}

// SetBudget gets a reference to the given NullableBudgetState and assigns it to the Budget field.
func (o *EstimateResponse) SetBudget(v BudgetState) {
	o.Budget.Set(&v)
}
// SetBudgetNil sets the value for Budget to be an explicit nil
func (o *EstimateResponse) SetBudgetNil() {
	o.Budget.Set(nil)
}

// UnsetBudget ensures that no value is present for Budget, not even an explicit nil
func (o *EstimateResponse) UnsetBudget() {
	o.Budget.Unset()
}

// GetCandidates returns the Candidates field value if set, zero value otherwise.
func (o *EstimateResponse) GetCandidates() []EstimateCandidate {
	if o == nil || IsNil(o.Candidates) {
		var ret []EstimateCandidate
		return ret
	}
	return o.Candidates
}

// GetCandidatesOk returns a tuple with the Candidates field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *EstimateResponse) GetCandidatesOk() ([]EstimateCandidate, bool) {
	if o == nil || IsNil(o.Candidates) {
		return nil, false
	}
	return o.Candidates, true
}

// HasCandidates returns a boolean if a field has been set.
func (o *EstimateResponse) HasCandidates() bool {
	if o != nil && !IsNil(o.Candidates) {
		return true
	}

	return false
}

// SetCandidates gets a reference to the given []EstimateCandidate and assigns it to the Candidates field.
func (o *EstimateResponse) SetCandidates(v []EstimateCandidate) {
	o.Candidates = v
}

// GetCurrency returns the Currency field value if set, zero value otherwise.
func (o *EstimateResponse) GetCurrency() string {
	if o == nil || IsNil(o.Currency) {
		var ret string
		return ret
	}
	return *o.Currency
}

// GetCurrencyOk returns a tuple with the Currency field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *EstimateResponse) GetCurrencyOk() (*string, bool) {
	if o == nil || IsNil(o.Currency) {
		return nil, false
	}
	return o.Currency, true
}

// HasCurrency returns a boolean if a field has been set.
func (o *EstimateResponse) HasCurrency() bool {
	if o != nil && !IsNil(o.Currency) {
		return true
	}

	return false
}

// SetCurrency gets a reference to the given string and assigns it to the Currency field.
func (o *EstimateResponse) SetCurrency(v string) {
	o.Currency = &v
}

// GetEstimatedCost returns the EstimatedCost field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *EstimateResponse) GetEstimatedCost() float32 {
	if o == nil || IsNil(o.EstimatedCost.Get()) {
		var ret float32
		return ret
	}
	return *o.EstimatedCost.Get()
}

// GetEstimatedCostOk returns a tuple with the EstimatedCost field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *EstimateResponse) GetEstimatedCostOk() (*float32, bool) {
	if o == nil {
		return nil, false
	}
	return o.EstimatedCost.Get(), o.EstimatedCost.IsSet()
}

// HasEstimatedCost returns a boolean if a field has been set.
func (o *EstimateResponse) HasEstimatedCost() bool {
	if o != nil && o.EstimatedCost.IsSet() {
		return true
	}

	return false
}

// SetEstimatedCost gets a reference to the given NullableFloat32 and assigns it to the EstimatedCost field.
func (o *EstimateResponse) SetEstimatedCost(v float32) {
	o.EstimatedCost.Set(&v)
}
// SetEstimatedCostNil sets the value for EstimatedCost to be an explicit nil
func (o *EstimateResponse) SetEstimatedCostNil() {
	o.EstimatedCost.Set(nil)
}

// UnsetEstimatedCost ensures that no value is present for EstimatedCost, not even an explicit nil
func (o *EstimateResponse) UnsetEstimatedCost() {
	o.EstimatedCost.Unset()
}

// GetModality returns the Modality field value
func (o *EstimateResponse) GetModality() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Modality
}

// GetModalityOk returns a tuple with the Modality field value
// and a boolean to check if the value has been set.
func (o *EstimateResponse) GetModalityOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Modality, true
}

// SetModality sets field value
func (o *EstimateResponse) SetModality(v string) {
	o.Modality = v
}

// GetModel returns the Model field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *EstimateResponse) GetModel() string {
	if o == nil || IsNil(o.Model.Get()) {
		var ret string
		return ret
	}
	return *o.Model.Get()
}

// GetModelOk returns a tuple with the Model field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *EstimateResponse) GetModelOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Model.Get(), o.Model.IsSet()
}

// HasModel returns a boolean if a field has been set.
func (o *EstimateResponse) HasModel() bool {
	if o != nil && o.Model.IsSet() {
		return true
	}

	return false
}

// SetModel gets a reference to the given NullableString and assigns it to the Model field.
func (o *EstimateResponse) SetModel(v string) {
	o.Model.Set(&v)
}
// SetModelNil sets the value for Model to be an explicit nil
func (o *EstimateResponse) SetModelNil() {
	o.Model.Set(nil)
}

// UnsetModel ensures that no value is present for Model, not even an explicit nil
func (o *EstimateResponse) UnsetModel() {
	o.Model.Unset()
}

// GetObject returns the Object field value if set, zero value otherwise.
func (o *EstimateResponse) GetObject() string {
	if o == nil || IsNil(o.Object) {
		var ret string
		return ret
	}
	return *o.Object
}

// GetObjectOk returns a tuple with the Object field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *EstimateResponse) GetObjectOk() (*string, bool) {
	if o == nil || IsNil(o.Object) {
		return nil, false
	}
	return o.Object, true
}

// HasObject returns a boolean if a field has been set.
func (o *EstimateResponse) HasObject() bool {
	if o != nil && !IsNil(o.Object) {
		return true
	}

	return false
}

// SetObject gets a reference to the given string and assigns it to the Object field.
func (o *EstimateResponse) SetObject(v string) {
	o.Object = &v
}

func (o EstimateResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o EstimateResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if o.Budget.IsSet() {
		toSerialize["budget"] = o.Budget.Get()
	}
	if !IsNil(o.Candidates) {
		toSerialize["candidates"] = o.Candidates
	}
	if !IsNil(o.Currency) {
		toSerialize["currency"] = o.Currency
	}
	if o.EstimatedCost.IsSet() {
		toSerialize["estimated_cost"] = o.EstimatedCost.Get()
	}
	toSerialize["modality"] = o.Modality
	if o.Model.IsSet() {
		toSerialize["model"] = o.Model.Get()
	}
	if !IsNil(o.Object) {
		toSerialize["object"] = o.Object
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *EstimateResponse) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"modality",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varEstimateResponse := _EstimateResponse{}

	err = json.Unmarshal(data, &varEstimateResponse)

	if err != nil {
		return err
	}

	*o = EstimateResponse(varEstimateResponse)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "budget")
		delete(additionalProperties, "candidates")
		delete(additionalProperties, "currency")
		delete(additionalProperties, "estimated_cost")
		delete(additionalProperties, "modality")
		delete(additionalProperties, "model")
		delete(additionalProperties, "object")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableEstimateResponse struct {
	value *EstimateResponse
	isSet bool
}

func (v NullableEstimateResponse) Get() *EstimateResponse {
	return v.value
}

func (v *NullableEstimateResponse) Set(val *EstimateResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableEstimateResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableEstimateResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableEstimateResponse(val *EstimateResponse) *NullableEstimateResponse {
	return &NullableEstimateResponse{value: val, isSet: true}
}

func (v NullableEstimateResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableEstimateResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


