/*
mm-gateway

Provider-neutral image, video, music, speech and voice cloning gateway.

API version: 0.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package mmgateway

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the ManagementUsageList type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ManagementUsageList{}

// ManagementUsageList struct for ManagementUsageList
type ManagementUsageList struct {
	Data []ManagedUsage `json:"data"`
	Object *string `json:"object,omitempty"`
}

type _ManagementUsageList ManagementUsageList

// NewManagementUsageList instantiates a new ManagementUsageList object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewManagementUsageList(data []ManagedUsage) *ManagementUsageList {
	this := ManagementUsageList{}
	this.Data = data
	var object string = "list"
	this.Object = &object
	return &this
}

// NewManagementUsageListWithDefaults instantiates a new ManagementUsageList object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewManagementUsageListWithDefaults() *ManagementUsageList {
	this := ManagementUsageList{}
	var object string = "list"
	this.Object = &object
	return &this
}

// GetData returns the Data field value
func (o *ManagementUsageList) GetData() []ManagedUsage {
	if o == nil {
		var ret []ManagedUsage
		return ret
	}

	return o.Data
}

// GetDataOk returns a tuple with the Data field value
// and a boolean to check if the value has been set.
func (o *ManagementUsageList) GetDataOk() ([]ManagedUsage, bool) {
	if o == nil {
		return nil, false
	}
	return o.Data, true
}

// SetData sets field value
func (o *ManagementUsageList) SetData(v []ManagedUsage) {
	o.Data = v
}

// GetObject returns the Object field value if set, zero value otherwise.
func (o *ManagementUsageList) GetObject() string {
	if o == nil || IsNil(o.Object) {
		var ret string
		return ret
	}
	return *o.Object
}

// GetObjectOk returns a tuple with the Object field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ManagementUsageList) GetObjectOk() (*string, bool) {
	if o == nil || IsNil(o.Object) {
		return nil, false
	}
	return o.Object, true
}

// HasObject returns a boolean if a field has been set.
func (o *ManagementUsageList) HasObject() bool {
	if o != nil && !IsNil(o.Object) {
		return true
	}

	return false
}

// SetObject gets a reference to the given string and assigns it to the Object field.
func (o *ManagementUsageList) SetObject(v string) {
	o.Object = &v
}

func (o ManagementUsageList) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ManagementUsageList) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["data"] = o.Data
	if !IsNil(o.Object) {
		toSerialize["object"] = o.Object
	}
	return toSerialize, nil
}

func (o *ManagementUsageList) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"data",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varManagementUsageList := _ManagementUsageList{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varManagementUsageList)

	if err != nil {
		return err
	}

	*o = ManagementUsageList(varManagementUsageList)

	return err
}

type NullableManagementUsageList struct {
	value *ManagementUsageList
	isSet bool
}

func (v NullableManagementUsageList) Get() *ManagementUsageList {
	return v.value
}

func (v *NullableManagementUsageList) Set(val *ManagementUsageList) {
	v.value = val
	v.isSet = true
}

func (v NullableManagementUsageList) IsSet() bool {
	return v.isSet
}

func (v *NullableManagementUsageList) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableManagementUsageList(val *ManagementUsageList) *NullableManagementUsageList {
	return &NullableManagementUsageList{value: val, isSet: true}
}

func (v NullableManagementUsageList) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableManagementUsageList) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


