/*
mm-gateway

Provider-neutral image, video, music, speech and voice cloning gateway.

API version: 0.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package mmgateway

import (
	"encoding/json"
)

// checks if the AudioParameters type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &AudioParameters{}

// AudioParameters struct for AudioParameters
type AudioParameters struct {
	BitrateKbps NullableInt32 `json:"bitrate_kbps,omitempty"`
	Delivery NullableString `json:"delivery,omitempty"`
	FileFormat NullableString `json:"file_format,omitempty"`
	Instructions NullableString `json:"instructions,omitempty"`
	Language NullableString `json:"language,omitempty" validate:"regexp=^[a-z]{2\\,3}(-[A-Za-z0-9]{2\\,8})*$"`
	SampleRateHz NullableInt32 `json:"sample_rate_hz,omitempty"`
	Seed NullableInt32 `json:"seed,omitempty"`
	Speed NullableFloat32 `json:"speed,omitempty"`
	// A gateway voice id from GET /v1/voices.
	Voice *string `json:"voice,omitempty" validate:"regexp=^[A-Za-z0-9][A-Za-z0-9._-]*$"`
}

// NewAudioParameters instantiates a new AudioParameters object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAudioParameters() *AudioParameters {
	this := AudioParameters{}
	var voice string = "default"
	this.Voice = &voice
	return &this
}

// NewAudioParametersWithDefaults instantiates a new AudioParameters object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAudioParametersWithDefaults() *AudioParameters {
	this := AudioParameters{}
	var voice string = "default"
	this.Voice = &voice
	return &this
}

// GetBitrateKbps returns the BitrateKbps field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *AudioParameters) GetBitrateKbps() int32 {
	if o == nil || IsNil(o.BitrateKbps.Get()) {
		var ret int32
		return ret
	}
	return *o.BitrateKbps.Get()
}

// GetBitrateKbpsOk returns a tuple with the BitrateKbps field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *AudioParameters) GetBitrateKbpsOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return o.BitrateKbps.Get(), o.BitrateKbps.IsSet()
}

// HasBitrateKbps returns a boolean if a field has been set.
func (o *AudioParameters) HasBitrateKbps() bool {
	if o != nil && o.BitrateKbps.IsSet() {
		return true
	}

	return false
}

// SetBitrateKbps gets a reference to the given NullableInt32 and assigns it to the BitrateKbps field.
func (o *AudioParameters) SetBitrateKbps(v int32) {
	o.BitrateKbps.Set(&v)
}
// SetBitrateKbpsNil sets the value for BitrateKbps to be an explicit nil
func (o *AudioParameters) SetBitrateKbpsNil() {
	o.BitrateKbps.Set(nil)
}

// UnsetBitrateKbps ensures that no value is present for BitrateKbps, not even an explicit nil
func (o *AudioParameters) UnsetBitrateKbps() {
	o.BitrateKbps.Unset()
}

// GetDelivery returns the Delivery field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *AudioParameters) GetDelivery() string {
	if o == nil || IsNil(o.Delivery.Get()) {
		var ret string
		return ret
	}
	return *o.Delivery.Get()
}

// GetDeliveryOk returns a tuple with the Delivery field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *AudioParameters) GetDeliveryOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Delivery.Get(), o.Delivery.IsSet()
}

// HasDelivery returns a boolean if a field has been set.
func (o *AudioParameters) HasDelivery() bool {
	if o != nil && o.Delivery.IsSet() {
		return true
	}

	return false
}

// SetDelivery gets a reference to the given NullableString and assigns it to the Delivery field.
func (o *AudioParameters) SetDelivery(v string) {
	o.Delivery.Set(&v)
}
// SetDeliveryNil sets the value for Delivery to be an explicit nil
func (o *AudioParameters) SetDeliveryNil() {
	o.Delivery.Set(nil)
}

// UnsetDelivery ensures that no value is present for Delivery, not even an explicit nil
func (o *AudioParameters) UnsetDelivery() {
	o.Delivery.Unset()
}

// GetFileFormat returns the FileFormat field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *AudioParameters) GetFileFormat() string {
	if o == nil || IsNil(o.FileFormat.Get()) {
		var ret string
		return ret
	}
	return *o.FileFormat.Get()
}

// GetFileFormatOk returns a tuple with the FileFormat field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *AudioParameters) GetFileFormatOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.FileFormat.Get(), o.FileFormat.IsSet()
}

// HasFileFormat returns a boolean if a field has been set.
func (o *AudioParameters) HasFileFormat() bool {
	if o != nil && o.FileFormat.IsSet() {
		return true
	}

	return false
}

// SetFileFormat gets a reference to the given NullableString and assigns it to the FileFormat field.
func (o *AudioParameters) SetFileFormat(v string) {
	o.FileFormat.Set(&v)
}
// SetFileFormatNil sets the value for FileFormat to be an explicit nil
func (o *AudioParameters) SetFileFormatNil() {
	o.FileFormat.Set(nil)
}

// UnsetFileFormat ensures that no value is present for FileFormat, not even an explicit nil
func (o *AudioParameters) UnsetFileFormat() {
	o.FileFormat.Unset()
}

// GetInstructions returns the Instructions field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *AudioParameters) GetInstructions() string {
	if o == nil || IsNil(o.Instructions.Get()) {
		var ret string
		return ret
	}
	return *o.Instructions.Get()
}

// GetInstructionsOk returns a tuple with the Instructions field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *AudioParameters) GetInstructionsOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Instructions.Get(), o.Instructions.IsSet()
}

// HasInstructions returns a boolean if a field has been set.
func (o *AudioParameters) HasInstructions() bool {
	if o != nil && o.Instructions.IsSet() {
		return true
	}

	return false
}

// SetInstructions gets a reference to the given NullableString and assigns it to the Instructions field.
func (o *AudioParameters) SetInstructions(v string) {
	o.Instructions.Set(&v)
}
// SetInstructionsNil sets the value for Instructions to be an explicit nil
func (o *AudioParameters) SetInstructionsNil() {
	o.Instructions.Set(nil)
}

// UnsetInstructions ensures that no value is present for Instructions, not even an explicit nil
func (o *AudioParameters) UnsetInstructions() {
	o.Instructions.Unset()
}

// GetLanguage returns the Language field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *AudioParameters) GetLanguage() string {
	if o == nil || IsNil(o.Language.Get()) {
		var ret string
		return ret
	}
	return *o.Language.Get()
}

// GetLanguageOk returns a tuple with the Language field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *AudioParameters) GetLanguageOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Language.Get(), o.Language.IsSet()
}

// HasLanguage returns a boolean if a field has been set.
func (o *AudioParameters) HasLanguage() bool {
	if o != nil && o.Language.IsSet() {
		return true
	}

	return false
}

// SetLanguage gets a reference to the given NullableString and assigns it to the Language field.
func (o *AudioParameters) SetLanguage(v string) {
	o.Language.Set(&v)
}
// SetLanguageNil sets the value for Language to be an explicit nil
func (o *AudioParameters) SetLanguageNil() {
	o.Language.Set(nil)
}

// UnsetLanguage ensures that no value is present for Language, not even an explicit nil
func (o *AudioParameters) UnsetLanguage() {
	o.Language.Unset()
}

// GetSampleRateHz returns the SampleRateHz field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *AudioParameters) GetSampleRateHz() int32 {
	if o == nil || IsNil(o.SampleRateHz.Get()) {
		var ret int32
		return ret
	}
	return *o.SampleRateHz.Get()
}

// GetSampleRateHzOk returns a tuple with the SampleRateHz field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *AudioParameters) GetSampleRateHzOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return o.SampleRateHz.Get(), o.SampleRateHz.IsSet()
}

// HasSampleRateHz returns a boolean if a field has been set.
func (o *AudioParameters) HasSampleRateHz() bool {
	if o != nil && o.SampleRateHz.IsSet() {
		return true
	}

	return false
}

// SetSampleRateHz gets a reference to the given NullableInt32 and assigns it to the SampleRateHz field.
func (o *AudioParameters) SetSampleRateHz(v int32) {
	o.SampleRateHz.Set(&v)
}
// SetSampleRateHzNil sets the value for SampleRateHz to be an explicit nil
func (o *AudioParameters) SetSampleRateHzNil() {
	o.SampleRateHz.Set(nil)
}

// UnsetSampleRateHz ensures that no value is present for SampleRateHz, not even an explicit nil
func (o *AudioParameters) UnsetSampleRateHz() {
	o.SampleRateHz.Unset()
}

// GetSeed returns the Seed field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *AudioParameters) GetSeed() int32 {
	if o == nil || IsNil(o.Seed.Get()) {
		var ret int32
		return ret
	}
	return *o.Seed.Get()
}

// GetSeedOk returns a tuple with the Seed field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *AudioParameters) GetSeedOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return o.Seed.Get(), o.Seed.IsSet()
}

// HasSeed returns a boolean if a field has been set.
func (o *AudioParameters) HasSeed() bool {
	if o != nil && o.Seed.IsSet() {
		return true
	}

	return false
}

// SetSeed gets a reference to the given NullableInt32 and assigns it to the Seed field.
func (o *AudioParameters) SetSeed(v int32) {
	o.Seed.Set(&v)
}
// SetSeedNil sets the value for Seed to be an explicit nil
func (o *AudioParameters) SetSeedNil() {
	o.Seed.Set(nil)
}

// UnsetSeed ensures that no value is present for Seed, not even an explicit nil
func (o *AudioParameters) UnsetSeed() {
	o.Seed.Unset()
}

// GetSpeed returns the Speed field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *AudioParameters) GetSpeed() float32 {
	if o == nil || IsNil(o.Speed.Get()) {
		var ret float32
		return ret
	}
	return *o.Speed.Get()
}

// GetSpeedOk returns a tuple with the Speed field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *AudioParameters) GetSpeedOk() (*float32, bool) {
	if o == nil {
		return nil, false
	}
	return o.Speed.Get(), o.Speed.IsSet()
}

// HasSpeed returns a boolean if a field has been set.
func (o *AudioParameters) HasSpeed() bool {
	if o != nil && o.Speed.IsSet() {
		return true
	}

	return false
}

// SetSpeed gets a reference to the given NullableFloat32 and assigns it to the Speed field.
func (o *AudioParameters) SetSpeed(v float32) {
	o.Speed.Set(&v)
}
// SetSpeedNil sets the value for Speed to be an explicit nil
func (o *AudioParameters) SetSpeedNil() {
	o.Speed.Set(nil)
}

// UnsetSpeed ensures that no value is present for Speed, not even an explicit nil
func (o *AudioParameters) UnsetSpeed() {
	o.Speed.Unset()
}

// GetVoice returns the Voice field value if set, zero value otherwise.
func (o *AudioParameters) GetVoice() string {
	if o == nil || IsNil(o.Voice) {
		var ret string
		return ret
	}
	return *o.Voice
}

// GetVoiceOk returns a tuple with the Voice field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AudioParameters) GetVoiceOk() (*string, bool) {
	if o == nil || IsNil(o.Voice) {
		return nil, false
	}
	return o.Voice, true
}

// HasVoice returns a boolean if a field has been set.
func (o *AudioParameters) HasVoice() bool {
	if o != nil && !IsNil(o.Voice) {
		return true
	}

	return false
}

// SetVoice gets a reference to the given string and assigns it to the Voice field.
func (o *AudioParameters) SetVoice(v string) {
	o.Voice = &v
}

func (o AudioParameters) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o AudioParameters) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if o.BitrateKbps.IsSet() {
		toSerialize["bitrate_kbps"] = o.BitrateKbps.Get()
	}
	if o.Delivery.IsSet() {
		toSerialize["delivery"] = o.Delivery.Get()
	}
	if o.FileFormat.IsSet() {
		toSerialize["file_format"] = o.FileFormat.Get()
	}
	if o.Instructions.IsSet() {
		toSerialize["instructions"] = o.Instructions.Get()
	}
	if o.Language.IsSet() {
		toSerialize["language"] = o.Language.Get()
	}
	if o.SampleRateHz.IsSet() {
		toSerialize["sample_rate_hz"] = o.SampleRateHz.Get()
	}
	if o.Seed.IsSet() {
		toSerialize["seed"] = o.Seed.Get()
	}
	if o.Speed.IsSet() {
		toSerialize["speed"] = o.Speed.Get()
	}
	if !IsNil(o.Voice) {
		toSerialize["voice"] = o.Voice
	}
	return toSerialize, nil
}

type NullableAudioParameters struct {
	value *AudioParameters
	isSet bool
}

func (v NullableAudioParameters) Get() *AudioParameters {
	return v.value
}

func (v *NullableAudioParameters) Set(val *AudioParameters) {
	v.value = val
	v.isSet = true
}

func (v NullableAudioParameters) IsSet() bool {
	return v.isSet
}

func (v *NullableAudioParameters) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAudioParameters(val *AudioParameters) *NullableAudioParameters {
	return &NullableAudioParameters{value: val, isSet: true}
}

func (v NullableAudioParameters) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAudioParameters) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


