/*
mm-gateway

Unified image, video, and music gateway with separate REST APIs.

API version: 0.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package mmgateway

import (
	"encoding/json"
	"fmt"
)

// checks if the ModelLimitsEntry type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ModelLimitsEntry{}

// ModelLimitsEntry A model catalogue entry enriched with its documented input/output limits.  ``limits`` carries the neutral limits the auto-router uses and that a client can consult when crafting a prompt for a specific model. Unknown limits are omitted; clients ignore unknown response members.
type ModelLimitsEntry struct {
	Id string `json:"id"`
	// Neutral input/output limits (modalities, max prompt, max output count, supported sizes/durations, role flags, ...).
	Limits map[string]interface{} `json:"limits,omitempty"`
	Modality string `json:"modality"`
	Object *string `json:"object,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _ModelLimitsEntry ModelLimitsEntry

// NewModelLimitsEntry instantiates a new ModelLimitsEntry object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewModelLimitsEntry(id string, modality string) *ModelLimitsEntry {
	this := ModelLimitsEntry{}
	this.Id = id
	this.Modality = modality
	var object string = "model"
	this.Object = &object
	return &this
}

// NewModelLimitsEntryWithDefaults instantiates a new ModelLimitsEntry object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewModelLimitsEntryWithDefaults() *ModelLimitsEntry {
	this := ModelLimitsEntry{}
	var object string = "model"
	this.Object = &object
	return &this
}

// GetId returns the Id field value
func (o *ModelLimitsEntry) GetId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *ModelLimitsEntry) GetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *ModelLimitsEntry) SetId(v string) {
	o.Id = v
}

// GetLimits returns the Limits field value if set, zero value otherwise.
func (o *ModelLimitsEntry) GetLimits() map[string]interface{} {
	if o == nil || IsNil(o.Limits) {
		var ret map[string]interface{}
		return ret
	}
	return o.Limits
}

// GetLimitsOk returns a tuple with the Limits field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ModelLimitsEntry) GetLimitsOk() (map[string]interface{}, bool) {
	if o == nil || IsNil(o.Limits) {
		return map[string]interface{}{}, false
	}
	return o.Limits, true
}

// HasLimits returns a boolean if a field has been set.
func (o *ModelLimitsEntry) HasLimits() bool {
	if o != nil && !IsNil(o.Limits) {
		return true
	}

	return false
}

// SetLimits gets a reference to the given map[string]interface{} and assigns it to the Limits field.
func (o *ModelLimitsEntry) SetLimits(v map[string]interface{}) {
	o.Limits = v
}

// GetModality returns the Modality field value
func (o *ModelLimitsEntry) GetModality() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Modality
}

// GetModalityOk returns a tuple with the Modality field value
// and a boolean to check if the value has been set.
func (o *ModelLimitsEntry) GetModalityOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Modality, true
}

// SetModality sets field value
func (o *ModelLimitsEntry) SetModality(v string) {
	o.Modality = v
}

// GetObject returns the Object field value if set, zero value otherwise.
func (o *ModelLimitsEntry) GetObject() string {
	if o == nil || IsNil(o.Object) {
		var ret string
		return ret
	}
	return *o.Object
}

// GetObjectOk returns a tuple with the Object field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ModelLimitsEntry) GetObjectOk() (*string, bool) {
	if o == nil || IsNil(o.Object) {
		return nil, false
	}
	return o.Object, true
}

// HasObject returns a boolean if a field has been set.
func (o *ModelLimitsEntry) HasObject() bool {
	if o != nil && !IsNil(o.Object) {
		return true
	}

	return false
}

// SetObject gets a reference to the given string and assigns it to the Object field.
func (o *ModelLimitsEntry) SetObject(v string) {
	o.Object = &v
}

func (o ModelLimitsEntry) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ModelLimitsEntry) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["id"] = o.Id
	if !IsNil(o.Limits) {
		toSerialize["limits"] = o.Limits
	}
	toSerialize["modality"] = o.Modality
	if !IsNil(o.Object) {
		toSerialize["object"] = o.Object
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *ModelLimitsEntry) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"id",
		"modality",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varModelLimitsEntry := _ModelLimitsEntry{}

	err = json.Unmarshal(data, &varModelLimitsEntry)

	if err != nil {
		return err
	}

	*o = ModelLimitsEntry(varModelLimitsEntry)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "id")
		delete(additionalProperties, "limits")
		delete(additionalProperties, "modality")
		delete(additionalProperties, "object")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableModelLimitsEntry struct {
	value *ModelLimitsEntry
	isSet bool
}

func (v NullableModelLimitsEntry) Get() *ModelLimitsEntry {
	return v.value
}

func (v *NullableModelLimitsEntry) Set(val *ModelLimitsEntry) {
	v.value = val
	v.isSet = true
}

func (v NullableModelLimitsEntry) IsSet() bool {
	return v.isSet
}

func (v *NullableModelLimitsEntry) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableModelLimitsEntry(val *ModelLimitsEntry) *NullableModelLimitsEntry {
	return &NullableModelLimitsEntry{value: val, isSet: true}
}

func (v NullableModelLimitsEntry) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableModelLimitsEntry) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


