/*
mm-gateway

Provider-neutral image, video, music, speech and voice cloning gateway.

API version: 0.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package mmgateway

import (
	"encoding/json"
)

// checks if the ManagedBudget type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ManagedBudget{}

// ManagedBudget struct for ManagedBudget
type ManagedBudget struct {
	LimitUsd NullableFloat32 `json:"limit_usd,omitempty"`
	Period *string `json:"period,omitempty"`
	ScopesLimitUsd NullableFloat32 `json:"scopes_limit_usd,omitempty"`
}

// NewManagedBudget instantiates a new ManagedBudget object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewManagedBudget() *ManagedBudget {
	this := ManagedBudget{}
	var period string = "month"
	this.Period = &period
	return &this
}

// NewManagedBudgetWithDefaults instantiates a new ManagedBudget object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewManagedBudgetWithDefaults() *ManagedBudget {
	this := ManagedBudget{}
	var period string = "month"
	this.Period = &period
	return &this
}

// GetLimitUsd returns the LimitUsd field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *ManagedBudget) GetLimitUsd() float32 {
	if o == nil || IsNil(o.LimitUsd.Get()) {
		var ret float32
		return ret
	}
	return *o.LimitUsd.Get()
}

// GetLimitUsdOk returns a tuple with the LimitUsd field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ManagedBudget) GetLimitUsdOk() (*float32, bool) {
	if o == nil {
		return nil, false
	}
	return o.LimitUsd.Get(), o.LimitUsd.IsSet()
}

// HasLimitUsd returns a boolean if a field has been set.
func (o *ManagedBudget) HasLimitUsd() bool {
	if o != nil && o.LimitUsd.IsSet() {
		return true
	}

	return false
}

// SetLimitUsd gets a reference to the given NullableFloat32 and assigns it to the LimitUsd field.
func (o *ManagedBudget) SetLimitUsd(v float32) {
	o.LimitUsd.Set(&v)
}
// SetLimitUsdNil sets the value for LimitUsd to be an explicit nil
func (o *ManagedBudget) SetLimitUsdNil() {
	o.LimitUsd.Set(nil)
}

// UnsetLimitUsd ensures that no value is present for LimitUsd, not even an explicit nil
func (o *ManagedBudget) UnsetLimitUsd() {
	o.LimitUsd.Unset()
}

// GetPeriod returns the Period field value if set, zero value otherwise.
func (o *ManagedBudget) GetPeriod() string {
	if o == nil || IsNil(o.Period) {
		var ret string
		return ret
	}
	return *o.Period
}

// GetPeriodOk returns a tuple with the Period field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ManagedBudget) GetPeriodOk() (*string, bool) {
	if o == nil || IsNil(o.Period) {
		return nil, false
	}
	return o.Period, true
}

// HasPeriod returns a boolean if a field has been set.
func (o *ManagedBudget) HasPeriod() bool {
	if o != nil && !IsNil(o.Period) {
		return true
	}

	return false
}

// SetPeriod gets a reference to the given string and assigns it to the Period field.
func (o *ManagedBudget) SetPeriod(v string) {
	o.Period = &v
}

// GetScopesLimitUsd returns the ScopesLimitUsd field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *ManagedBudget) GetScopesLimitUsd() float32 {
	if o == nil || IsNil(o.ScopesLimitUsd.Get()) {
		var ret float32
		return ret
	}
	return *o.ScopesLimitUsd.Get()
}

// GetScopesLimitUsdOk returns a tuple with the ScopesLimitUsd field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ManagedBudget) GetScopesLimitUsdOk() (*float32, bool) {
	if o == nil {
		return nil, false
	}
	return o.ScopesLimitUsd.Get(), o.ScopesLimitUsd.IsSet()
}

// HasScopesLimitUsd returns a boolean if a field has been set.
func (o *ManagedBudget) HasScopesLimitUsd() bool {
	if o != nil && o.ScopesLimitUsd.IsSet() {
		return true
	}

	return false
}

// SetScopesLimitUsd gets a reference to the given NullableFloat32 and assigns it to the ScopesLimitUsd field.
func (o *ManagedBudget) SetScopesLimitUsd(v float32) {
	o.ScopesLimitUsd.Set(&v)
}
// SetScopesLimitUsdNil sets the value for ScopesLimitUsd to be an explicit nil
func (o *ManagedBudget) SetScopesLimitUsdNil() {
	o.ScopesLimitUsd.Set(nil)
}

// UnsetScopesLimitUsd ensures that no value is present for ScopesLimitUsd, not even an explicit nil
func (o *ManagedBudget) UnsetScopesLimitUsd() {
	o.ScopesLimitUsd.Unset()
}

func (o ManagedBudget) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ManagedBudget) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if o.LimitUsd.IsSet() {
		toSerialize["limit_usd"] = o.LimitUsd.Get()
	}
	if !IsNil(o.Period) {
		toSerialize["period"] = o.Period
	}
	if o.ScopesLimitUsd.IsSet() {
		toSerialize["scopes_limit_usd"] = o.ScopesLimitUsd.Get()
	}
	return toSerialize, nil
}

type NullableManagedBudget struct {
	value *ManagedBudget
	isSet bool
}

func (v NullableManagedBudget) Get() *ManagedBudget {
	return v.value
}

func (v *NullableManagedBudget) Set(val *ManagedBudget) {
	v.value = val
	v.isSet = true
}

func (v NullableManagedBudget) IsSet() bool {
	return v.isSet
}

func (v *NullableManagedBudget) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableManagedBudget(val *ManagedBudget) *NullableManagedBudget {
	return &NullableManagedBudget{value: val, isSet: true}
}

func (v NullableManagedBudget) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableManagedBudget) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


