/*
mm-gateway

Provider-neutral image, video, music, speech and voice cloning gateway.

API version: 0.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package mmgateway

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the ManagedUsage type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ManagedUsage{}

// ManagedUsage struct for ManagedUsage
type ManagedUsage struct {
	Enabled bool `json:"enabled"`
	KeyId string `json:"key_id"`
	Usage UsageResponse `json:"usage"`
}

type _ManagedUsage ManagedUsage

// NewManagedUsage instantiates a new ManagedUsage object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewManagedUsage(enabled bool, keyId string, usage UsageResponse) *ManagedUsage {
	this := ManagedUsage{}
	this.Enabled = enabled
	this.KeyId = keyId
	this.Usage = usage
	return &this
}

// NewManagedUsageWithDefaults instantiates a new ManagedUsage object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewManagedUsageWithDefaults() *ManagedUsage {
	this := ManagedUsage{}
	return &this
}

// GetEnabled returns the Enabled field value
func (o *ManagedUsage) GetEnabled() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.Enabled
}

// GetEnabledOk returns a tuple with the Enabled field value
// and a boolean to check if the value has been set.
func (o *ManagedUsage) GetEnabledOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Enabled, true
}

// SetEnabled sets field value
func (o *ManagedUsage) SetEnabled(v bool) {
	o.Enabled = v
}

// GetKeyId returns the KeyId field value
func (o *ManagedUsage) GetKeyId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.KeyId
}

// GetKeyIdOk returns a tuple with the KeyId field value
// and a boolean to check if the value has been set.
func (o *ManagedUsage) GetKeyIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.KeyId, true
}

// SetKeyId sets field value
func (o *ManagedUsage) SetKeyId(v string) {
	o.KeyId = v
}

// GetUsage returns the Usage field value
func (o *ManagedUsage) GetUsage() UsageResponse {
	if o == nil {
		var ret UsageResponse
		return ret
	}

	return o.Usage
}

// GetUsageOk returns a tuple with the Usage field value
// and a boolean to check if the value has been set.
func (o *ManagedUsage) GetUsageOk() (*UsageResponse, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Usage, true
}

// SetUsage sets field value
func (o *ManagedUsage) SetUsage(v UsageResponse) {
	o.Usage = v
}

func (o ManagedUsage) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ManagedUsage) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["enabled"] = o.Enabled
	toSerialize["key_id"] = o.KeyId
	toSerialize["usage"] = o.Usage
	return toSerialize, nil
}

func (o *ManagedUsage) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"enabled",
		"key_id",
		"usage",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varManagedUsage := _ManagedUsage{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varManagedUsage)

	if err != nil {
		return err
	}

	*o = ManagedUsage(varManagedUsage)

	return err
}

type NullableManagedUsage struct {
	value *ManagedUsage
	isSet bool
}

func (v NullableManagedUsage) Get() *ManagedUsage {
	return v.value
}

func (v *NullableManagedUsage) Set(val *ManagedUsage) {
	v.value = val
	v.isSet = true
}

func (v NullableManagedUsage) IsSet() bool {
	return v.isSet
}

func (v *NullableManagedUsage) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableManagedUsage(val *ManagedUsage) *NullableManagedUsage {
	return &NullableManagedUsage{value: val, isSet: true}
}

func (v NullableManagedUsage) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableManagedUsage) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


