/*
mm-gateway

Provider-neutral image, video, music, speech and voice cloning gateway.

API version: 0.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package mmgateway

import (
	"encoding/json"
	"fmt"
)

// checks if the ModelLimitsListResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ModelLimitsListResponse{}

// ModelLimitsListResponse struct for ModelLimitsListResponse
type ModelLimitsListResponse struct {
	Data []ModelLimitsEntry `json:"data"`
	Object *string `json:"object,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _ModelLimitsListResponse ModelLimitsListResponse

// NewModelLimitsListResponse instantiates a new ModelLimitsListResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewModelLimitsListResponse(data []ModelLimitsEntry) *ModelLimitsListResponse {
	this := ModelLimitsListResponse{}
	this.Data = data
	var object string = "list"
	this.Object = &object
	return &this
}

// NewModelLimitsListResponseWithDefaults instantiates a new ModelLimitsListResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewModelLimitsListResponseWithDefaults() *ModelLimitsListResponse {
	this := ModelLimitsListResponse{}
	var object string = "list"
	this.Object = &object
	return &this
}

// GetData returns the Data field value
func (o *ModelLimitsListResponse) GetData() []ModelLimitsEntry {
	if o == nil {
		var ret []ModelLimitsEntry
		return ret
	}

	return o.Data
}

// GetDataOk returns a tuple with the Data field value
// and a boolean to check if the value has been set.
func (o *ModelLimitsListResponse) GetDataOk() ([]ModelLimitsEntry, bool) {
	if o == nil {
		return nil, false
	}
	return o.Data, true
}

// SetData sets field value
func (o *ModelLimitsListResponse) SetData(v []ModelLimitsEntry) {
	o.Data = v
}

// GetObject returns the Object field value if set, zero value otherwise.
func (o *ModelLimitsListResponse) GetObject() string {
	if o == nil || IsNil(o.Object) {
		var ret string
		return ret
	}
	return *o.Object
}

// GetObjectOk returns a tuple with the Object field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ModelLimitsListResponse) GetObjectOk() (*string, bool) {
	if o == nil || IsNil(o.Object) {
		return nil, false
	}
	return o.Object, true
}

// HasObject returns a boolean if a field has been set.
func (o *ModelLimitsListResponse) HasObject() bool {
	if o != nil && !IsNil(o.Object) {
		return true
	}

	return false
}

// SetObject gets a reference to the given string and assigns it to the Object field.
func (o *ModelLimitsListResponse) SetObject(v string) {
	o.Object = &v
}

func (o ModelLimitsListResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ModelLimitsListResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["data"] = o.Data
	if !IsNil(o.Object) {
		toSerialize["object"] = o.Object
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *ModelLimitsListResponse) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"data",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varModelLimitsListResponse := _ModelLimitsListResponse{}

	err = json.Unmarshal(data, &varModelLimitsListResponse)

	if err != nil {
		return err
	}

	*o = ModelLimitsListResponse(varModelLimitsListResponse)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "data")
		delete(additionalProperties, "object")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableModelLimitsListResponse struct {
	value *ModelLimitsListResponse
	isSet bool
}

func (v NullableModelLimitsListResponse) Get() *ModelLimitsListResponse {
	return v.value
}

func (v *NullableModelLimitsListResponse) Set(val *ModelLimitsListResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableModelLimitsListResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableModelLimitsListResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableModelLimitsListResponse(val *ModelLimitsListResponse) *NullableModelLimitsListResponse {
	return &NullableModelLimitsListResponse{value: val, isSet: true}
}

func (v NullableModelLimitsListResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableModelLimitsListResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


