/*
mm-gateway

Provider-neutral image, video, music, speech and voice cloning gateway.

API version: 0.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package mmgateway

import (
	"encoding/json"
	"fmt"
)

// checks if the ImageOutput type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ImageOutput{}

// ImageOutput struct for ImageOutput
type ImageOutput struct {
	MimeType NullableString `json:"mime_type,omitempty"`
	RevisedPrompt NullableString `json:"revised_prompt,omitempty"`
	// Absolute media URI. Inline media uses a base64 data URI.
	Uri string `json:"uri"`
	AdditionalProperties map[string]interface{}
}

type _ImageOutput ImageOutput

// NewImageOutput instantiates a new ImageOutput object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewImageOutput(uri string) *ImageOutput {
	this := ImageOutput{}
	this.Uri = uri
	return &this
}

// NewImageOutputWithDefaults instantiates a new ImageOutput object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewImageOutputWithDefaults() *ImageOutput {
	this := ImageOutput{}
	return &this
}

// GetMimeType returns the MimeType field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *ImageOutput) GetMimeType() string {
	if o == nil || IsNil(o.MimeType.Get()) {
		var ret string
		return ret
	}
	return *o.MimeType.Get()
}

// GetMimeTypeOk returns a tuple with the MimeType field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ImageOutput) GetMimeTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.MimeType.Get(), o.MimeType.IsSet()
}

// HasMimeType returns a boolean if a field has been set.
func (o *ImageOutput) HasMimeType() bool {
	if o != nil && o.MimeType.IsSet() {
		return true
	}

	return false
}

// SetMimeType gets a reference to the given NullableString and assigns it to the MimeType field.
func (o *ImageOutput) SetMimeType(v string) {
	o.MimeType.Set(&v)
}
// SetMimeTypeNil sets the value for MimeType to be an explicit nil
func (o *ImageOutput) SetMimeTypeNil() {
	o.MimeType.Set(nil)
}

// UnsetMimeType ensures that no value is present for MimeType, not even an explicit nil
func (o *ImageOutput) UnsetMimeType() {
	o.MimeType.Unset()
}

// GetRevisedPrompt returns the RevisedPrompt field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *ImageOutput) GetRevisedPrompt() string {
	if o == nil || IsNil(o.RevisedPrompt.Get()) {
		var ret string
		return ret
	}
	return *o.RevisedPrompt.Get()
}

// GetRevisedPromptOk returns a tuple with the RevisedPrompt field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ImageOutput) GetRevisedPromptOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.RevisedPrompt.Get(), o.RevisedPrompt.IsSet()
}

// HasRevisedPrompt returns a boolean if a field has been set.
func (o *ImageOutput) HasRevisedPrompt() bool {
	if o != nil && o.RevisedPrompt.IsSet() {
		return true
	}

	return false
}

// SetRevisedPrompt gets a reference to the given NullableString and assigns it to the RevisedPrompt field.
func (o *ImageOutput) SetRevisedPrompt(v string) {
	o.RevisedPrompt.Set(&v)
}
// SetRevisedPromptNil sets the value for RevisedPrompt to be an explicit nil
func (o *ImageOutput) SetRevisedPromptNil() {
	o.RevisedPrompt.Set(nil)
}

// UnsetRevisedPrompt ensures that no value is present for RevisedPrompt, not even an explicit nil
func (o *ImageOutput) UnsetRevisedPrompt() {
	o.RevisedPrompt.Unset()
}

// GetUri returns the Uri field value
func (o *ImageOutput) GetUri() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Uri
}

// GetUriOk returns a tuple with the Uri field value
// and a boolean to check if the value has been set.
func (o *ImageOutput) GetUriOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Uri, true
}

// SetUri sets field value
func (o *ImageOutput) SetUri(v string) {
	o.Uri = v
}

func (o ImageOutput) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ImageOutput) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if o.MimeType.IsSet() {
		toSerialize["mime_type"] = o.MimeType.Get()
	}
	if o.RevisedPrompt.IsSet() {
		toSerialize["revised_prompt"] = o.RevisedPrompt.Get()
	}
	toSerialize["uri"] = o.Uri

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *ImageOutput) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"uri",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varImageOutput := _ImageOutput{}

	err = json.Unmarshal(data, &varImageOutput)

	if err != nil {
		return err
	}

	*o = ImageOutput(varImageOutput)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "mime_type")
		delete(additionalProperties, "revised_prompt")
		delete(additionalProperties, "uri")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableImageOutput struct {
	value *ImageOutput
	isSet bool
}

func (v NullableImageOutput) Get() *ImageOutput {
	return v.value
}

func (v *NullableImageOutput) Set(val *ImageOutput) {
	v.value = val
	v.isSet = true
}

func (v NullableImageOutput) IsSet() bool {
	return v.isSet
}

func (v *NullableImageOutput) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableImageOutput(val *ImageOutput) *NullableImageOutput {
	return &NullableImageOutput{value: val, isSet: true}
}

func (v NullableImageOutput) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableImageOutput) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


