/*
mm-gateway

Provider-neutral image, video, music, speech and voice cloning gateway.

API version: 0.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package mmgateway

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the CounterSample type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CounterSample{}

// CounterSample struct for CounterSample
type CounterSample struct {
	Labels map[string]string `json:"labels"`
	Name string `json:"name"`
	Value float32 `json:"value"`
}

type _CounterSample CounterSample

// NewCounterSample instantiates a new CounterSample object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCounterSample(labels map[string]string, name string, value float32) *CounterSample {
	this := CounterSample{}
	this.Labels = labels
	this.Name = name
	this.Value = value
	return &this
}

// NewCounterSampleWithDefaults instantiates a new CounterSample object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCounterSampleWithDefaults() *CounterSample {
	this := CounterSample{}
	return &this
}

// GetLabels returns the Labels field value
func (o *CounterSample) GetLabels() map[string]string {
	if o == nil {
		var ret map[string]string
		return ret
	}

	return o.Labels
}

// GetLabelsOk returns a tuple with the Labels field value
// and a boolean to check if the value has been set.
func (o *CounterSample) GetLabelsOk() (map[string]string, bool) {
	if o == nil {
		return map[string]string{}, false
	}
	return o.Labels, true
}

// SetLabels sets field value
func (o *CounterSample) SetLabels(v map[string]string) {
	o.Labels = v
}

// GetName returns the Name field value
func (o *CounterSample) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *CounterSample) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *CounterSample) SetName(v string) {
	o.Name = v
}

// GetValue returns the Value field value
func (o *CounterSample) GetValue() float32 {
	if o == nil {
		var ret float32
		return ret
	}

	return o.Value
}

// GetValueOk returns a tuple with the Value field value
// and a boolean to check if the value has been set.
func (o *CounterSample) GetValueOk() (*float32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Value, true
}

// SetValue sets field value
func (o *CounterSample) SetValue(v float32) {
	o.Value = v
}

func (o CounterSample) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CounterSample) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["labels"] = o.Labels
	toSerialize["name"] = o.Name
	toSerialize["value"] = o.Value
	return toSerialize, nil
}

func (o *CounterSample) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"labels",
		"name",
		"value",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varCounterSample := _CounterSample{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varCounterSample)

	if err != nil {
		return err
	}

	*o = CounterSample(varCounterSample)

	return err
}

type NullableCounterSample struct {
	value *CounterSample
	isSet bool
}

func (v NullableCounterSample) Get() *CounterSample {
	return v.value
}

func (v *NullableCounterSample) Set(val *CounterSample) {
	v.value = val
	v.isSet = true
}

func (v NullableCounterSample) IsSet() bool {
	return v.isSet
}

func (v *NullableCounterSample) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCounterSample(val *CounterSample) *NullableCounterSample {
	return &NullableCounterSample{value: val, isSet: true}
}

func (v NullableCounterSample) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCounterSample) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


