/*
mm-gateway

Provider-neutral image, video, music, speech and voice cloning gateway.

API version: 0.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package mmgateway

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the ManagementMetrics type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ManagementMetrics{}

// ManagementMetrics struct for ManagementMetrics
type ManagementMetrics struct {
	CollectedAt string `json:"collected_at"`
	Counters []CounterSample `json:"counters"`
	Enabled bool `json:"enabled"`
	Histograms []HistogramSample `json:"histograms"`
	Selection []SelectionHealth `json:"selection"`
}

type _ManagementMetrics ManagementMetrics

// NewManagementMetrics instantiates a new ManagementMetrics object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewManagementMetrics(collectedAt string, counters []CounterSample, enabled bool, histograms []HistogramSample, selection []SelectionHealth) *ManagementMetrics {
	this := ManagementMetrics{}
	this.CollectedAt = collectedAt
	this.Counters = counters
	this.Enabled = enabled
	this.Histograms = histograms
	this.Selection = selection
	return &this
}

// NewManagementMetricsWithDefaults instantiates a new ManagementMetrics object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewManagementMetricsWithDefaults() *ManagementMetrics {
	this := ManagementMetrics{}
	return &this
}

// GetCollectedAt returns the CollectedAt field value
func (o *ManagementMetrics) GetCollectedAt() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.CollectedAt
}

// GetCollectedAtOk returns a tuple with the CollectedAt field value
// and a boolean to check if the value has been set.
func (o *ManagementMetrics) GetCollectedAtOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.CollectedAt, true
}

// SetCollectedAt sets field value
func (o *ManagementMetrics) SetCollectedAt(v string) {
	o.CollectedAt = v
}

// GetCounters returns the Counters field value
func (o *ManagementMetrics) GetCounters() []CounterSample {
	if o == nil {
		var ret []CounterSample
		return ret
	}

	return o.Counters
}

// GetCountersOk returns a tuple with the Counters field value
// and a boolean to check if the value has been set.
func (o *ManagementMetrics) GetCountersOk() ([]CounterSample, bool) {
	if o == nil {
		return nil, false
	}
	return o.Counters, true
}

// SetCounters sets field value
func (o *ManagementMetrics) SetCounters(v []CounterSample) {
	o.Counters = v
}

// GetEnabled returns the Enabled field value
func (o *ManagementMetrics) GetEnabled() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.Enabled
}

// GetEnabledOk returns a tuple with the Enabled field value
// and a boolean to check if the value has been set.
func (o *ManagementMetrics) GetEnabledOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Enabled, true
}

// SetEnabled sets field value
func (o *ManagementMetrics) SetEnabled(v bool) {
	o.Enabled = v
}

// GetHistograms returns the Histograms field value
func (o *ManagementMetrics) GetHistograms() []HistogramSample {
	if o == nil {
		var ret []HistogramSample
		return ret
	}

	return o.Histograms
}

// GetHistogramsOk returns a tuple with the Histograms field value
// and a boolean to check if the value has been set.
func (o *ManagementMetrics) GetHistogramsOk() ([]HistogramSample, bool) {
	if o == nil {
		return nil, false
	}
	return o.Histograms, true
}

// SetHistograms sets field value
func (o *ManagementMetrics) SetHistograms(v []HistogramSample) {
	o.Histograms = v
}

// GetSelection returns the Selection field value
func (o *ManagementMetrics) GetSelection() []SelectionHealth {
	if o == nil {
		var ret []SelectionHealth
		return ret
	}

	return o.Selection
}

// GetSelectionOk returns a tuple with the Selection field value
// and a boolean to check if the value has been set.
func (o *ManagementMetrics) GetSelectionOk() ([]SelectionHealth, bool) {
	if o == nil {
		return nil, false
	}
	return o.Selection, true
}

// SetSelection sets field value
func (o *ManagementMetrics) SetSelection(v []SelectionHealth) {
	o.Selection = v
}

func (o ManagementMetrics) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ManagementMetrics) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["collected_at"] = o.CollectedAt
	toSerialize["counters"] = o.Counters
	toSerialize["enabled"] = o.Enabled
	toSerialize["histograms"] = o.Histograms
	toSerialize["selection"] = o.Selection
	return toSerialize, nil
}

func (o *ManagementMetrics) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"collected_at",
		"counters",
		"enabled",
		"histograms",
		"selection",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varManagementMetrics := _ManagementMetrics{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varManagementMetrics)

	if err != nil {
		return err
	}

	*o = ManagementMetrics(varManagementMetrics)

	return err
}

type NullableManagementMetrics struct {
	value *ManagementMetrics
	isSet bool
}

func (v NullableManagementMetrics) Get() *ManagementMetrics {
	return v.value
}

func (v *NullableManagementMetrics) Set(val *ManagementMetrics) {
	v.value = val
	v.isSet = true
}

func (v NullableManagementMetrics) IsSet() bool {
	return v.isSet
}

func (v *NullableManagementMetrics) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableManagementMetrics(val *ManagementMetrics) *NullableManagementMetrics {
	return &NullableManagementMetrics{value: val, isSet: true}
}

func (v NullableManagementMetrics) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableManagementMetrics) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


